<div class="content-box">
	<h3 id="buildings" class="content-box-header bg-primary" style="text-align: left;">
		<i class="glyph-icon icon-users"></i>
		BUILDING OWNERS
		<div class="header-buttons-separator">
			<a class="icon-separator" href="javascript:cmp_company.showNewDialog();">
				<i class="glyph-icon icon-plus"></i>
            </a>

            <a class="icon-separator" href="<?php echo App::baseUrl() ?>/company/excelexport?gridId=company" target='_blank'>
				<i class="glyph-icon fa-file-excel-o"></i>
			</a>

			<!-- <a class="icon-separator" href="javascript:bratiliusDialog.showSearch(
				'<?php //echo App::baseUrl() ?>/company/search?_model=company', 'cmp_company');">
				<i class="glyph-icon icon-search"></i>
            </a> -->
					<div class="table-maindiv">

            <input type="text" name="search-inspection" class="searchtable" id="search_inspection" placeholder="Search for Owner" value="<?php echo nvl($this->gridParams['NAME'], '') ?>">
			<a href="#" class="" id="searchInspectionBtn"><i class="glyph-icon icon-search"></i></a>	

</div>
			
		</div>
	</h3>
	
	<div class="content-box-wrapper">
		<div class="row">
			<div id="list_of_owners" jsId="list_of_owners" dojoType="dijit.layout.ContentPane" href="<?= App::baseUrl() ?>/company/owners"></div>
		</div>
	</div>
	
</div>

		<!-- SUBMIT DIALOG -->
					<div id="dialogSubmit" dojoType="dijit.Dialog">

						<div class="content-box">

							<h3 class="content-box-header bg-primary" style="text-align: left;">
								<i class="glyph-icon icon-lock"></i>
								Lock
								<div class="header-buttons-separator">

							<!-- 	<a class="icon-separator" href="javascript:dialogSubmit.hide();">
									<i class="glyph-icon icon-remove"></i>
								</a> -->
							</div>
						</h3>

						<div class="modal-body importpopup" >
							<div class="row">
								<div class="col-sm-12" style="padding-top: 20px;">
									<label id="lblInfo"></label>
								</div>
								<div class="col-sm-12" style="padding-top: 20px;text-align: center;">

									<button dojoType="dijit.form.Button" class="short" type="submit">OK</button>

								</div>
							</div>






							
							
						</div>
					</div>

					</div>


<script type="text/javascript">
	$(document).ready(function() {

		$("#searchInspectionBtn").click(function(e){
			searchInspection();	
		});

		$('#search_inspection').on('keypress', function(e) {           
			var code = e.keyCode || e.which;
			if(code==13){
				searchInspection();  
			}
		});
	});


	function searchInspection(){
		var search = $("#search_inspection").val();
		bratiliusDialog.setGrid("cmp_company");
		var elements = {
			"NAME":"*"+search+"*",
			"PRIMARY_CONTACT_LAST_NAME":"*"+search+"*",
			"ADDRESS_1":"*"+search+"*",
			// "ADDRESS_2":"*"+search+"*",
			"CITY":"*"+search+"*",
			"STATE":"*"+search+"*"		
		}
		
		bratiliusDialog.executeSearch(elements)
	}

</script>



