<div class="content-box">

	<div class="content-box-wrapper">
		
		<ul class="nav nav-tabs">
			<li class="active"><a href="#owner_inspections_tab" aria-controls="owner_inspections_tab" role="tab" data-toggle="tab">Inspections</a></li>
			<li><a href="#owner_buildings_tab" aria-controls="owner_buildings_tab" role="tab" data-toggle="tab">Buildings</a></li>
			<li><a href="#owner_employees_tab" aria-controls="owner_employees_tab" role="tab" data-toggle="tab">Employees</a></li>
			<li><a href="#owner_company_tab" aria-controls="owner_company_tab" role="tab" data-toggle="tab">Company</a></li>
		</ul>
		
		<h3 style="margin-top: 10px; margin-bottom: 10px;"><?= $this->companyName ?></h3>
		
		<!-- Tab panes -->
		<div class="tab-content">

			<!-- Inspections Tab Start -->
			<div role="tabpanel" class="tab-pane active" id="owner_inspections_tab">
				<div class="content-box">
					<h3 id="inspections" class="content-box-header bg-primary" style="text-align: left;">
						<i class="fa fa-edit"></i>
						INSPECTIONS
						<div class="header-buttons-separator">
							<a class="icon-separator" href="javascript:cmp_company_inspections.showNewDialog(<?= $this->companyId ?>);">
								<i class="glyph-icon icon-plus"></i>
							</a>
							<a class="icon-separator" href="<?php echo App::baseUrl() ?>/company/excelexport?gridId=company_inspections&_parent=<?= $this->companyId ?>" target='_blank'>
								<i class="glyph-icon fa-file-excel-o"></i>
							</a>
							<div class="table-maindiv">
								<input type="text" name="search-inspection" class="searchtable" id="search_inspection" placeholder="Search for Inspection">
								<a href="#" class="" id="searchInspectionBtn"><i class="glyph-icon icon-search"></i></a>	
							</div>
						</div>
					</h3>

					<div class="content-box-wrapper">
						<div class="row">
							<div id="owner_list_of_inspections" jsId="owner_list_of_inspections" dojoType="dijit.layout.ContentPane" href="<?= $this->baseUrl ?>/company/inspections?_parent=<?= $this->companyId ?>"></div>
						</div>
					</div>
					<!-- <ul class="nav nav-tabs">
						<li class="active"><a href="#owner_inspection_doors_tab" aria-controls="owner_inspection_doors_tab" role="tab" data-toggle="tab">Doors</a></li>

						<li><a href="#owner_inspection_history_tab" aria-controls="owner_inspection_history_tab" role="tab" data-toggle="tab">History</a></li>
					</ul> -->

					<!-- Inspection Tab panes -->
					<!-- <div class="tab-content"> -->
						<div role="tabpanel" class="tab-pane active" id="owner_inspection_doors_tab">
							<div class="content-box">
								<h3  class="content-box-header bg-primary" style="text-align: left;">
								<!-- 	<i class="fa fa-columns"></i>

									DOORS -->
									<a class="activeT" id="doors_header" href="#"><i class="fa fa-columns"></i>
									DOORS</a>
									<a href="#" id="history_header" style="text-align: left;">
										<i class="glyph-icon icon-history"></i>
										HISTORY
									</a>
									<div style="display: inline-block;">
										<div class="header-buttons-separator door-header">

											<a class="icon-separator" href="javascript:cmp_company_doors.showNewDialog();">
												<i class="glyph-icon icon-plus"></i>
											</a>
											<a class="icon-separator  door-excel-export" href="<?php echo App::baseUrl() ?>/company/excelexport?gridId=company_doors" target='_blank'>
												<i class="glyph-icon fa-file-excel-o"></i>
											</a>

											<div class="table-maindiv">
												<input type="text" name="search-inspection" class="searchtable" id="search_door" placeholder="Search for Door">
												<a href="#" class="" id="searchDoorBtn"><i class="glyph-icon icon-search"></i></a>
											</div>

										</div>
										<div class="header-buttons-separator histroy-header" hidden>
													<!-- <a class="icon-separator" href="javascript:bratiliusDialog.showSearch(
													'<?php //echo App::baseUrl() ?>/inspection/search?_model=inspection_inspects', 'cmp_inspection_inspects');">
													<i class="glyph-icon icon-search"></i>
												</a> -->
												<a class="icon-separator history-excel-export" href="<?php echo App::baseUrl() ?>/company/excelexport?gridId=company_history" target='_blank'>
													<i class="glyph-icon fa-file-excel-o"></i>
												</a>
												<div class="table-maindiv">
													<input type="text" name="search-inspection" class="searchtable" id="search_history" placeholder="Search for History">
													<a href="#" class="" id="searchHistoryBtn"><i class="glyph-icon icon-search"></i></a>	
												</div>

											</div>

										</div>
									</h3>

									<div class="content-box-wrapper door-detail">
										<div class="row">
											<div id="company_list_of_doors" jsId="company_list_of_doors" dojoType="dijit.layout.ContentPane" href="<?= App::baseUrl() ?>/company/doors?_super=-1"></div>
										</div>
									</div>



						<!-- 	</div>
						</div> -->
						<!--End Of Doors Tab -->


						<!--Begining Of History Tab -->
					<!-- 	<div role="tabpanel" class="tab-pane" id="owner_inspection_history_tab">
							<div class="content-box">
								<h3 id="doors_header" class="content-box-header bg-primary" style="text-align: left;">
									<i class="fa fa-columns"></i>

									HISTORY

								</h3> -->

								<div class="content-box-wrapper histroy-detail" hidden>
									<div class="row">
										<div id="company_list_of_doors_history" jsId="company_list_of_doors" dojoType="dijit.layout.ContentPane" href="<?= App::baseUrl() ?>/company/changes?_super=-1"></div>
									</div>
								</div>



							</div>
						</div><!--End Of History Tab -->





						<!-- </div> -->
						<!-- End of Inspection Tab panes -->

					</div>




				</div><!-- Inspections Tab End -->

				<div role="tabpanel" class="tab-pane" id="owner_buildings_tab">

					<div class="content-box">
						<h3 id="buildings" class="content-box-header bg-primary" style="text-align: left;">
							<i class="glyph-icon icon-building"></i>
							BUILDINGS
							<div class="header-buttons-separator">

								<a class="icon-separator" href="javascript:cmp_company_buildings.showNewDialog(<?= $this->companyId ?>);">
									<i class="glyph-icon icon-plus"></i>
								</a>
								<a class="icon-separator" href="<?php echo App::baseUrl() ?>/company/excelexport?gridId=company_buildings&_parent=<?= $this->companyId ?>" target='_blank'>
									<i class="glyph-icon fa-file-excel-o"></i>
								</a>
								<div class="table-maindiv">
									<input type="text" name="search-inspection" class="searchtable" id="search_building" placeholder="Search for Building">
									<a href="#" class="" id="searchBuildingBtn"><i class="glyph-icon icon-search"></i></a>	
								</div>

							</div>
						</h3>

						<div class="content-box-wrapper">
							<div class="row">
								<div id="owner_list_of_buildings" jsId="owner_list_of_buildings" dojoType="dijit.layout.ContentPane" href="<?= App::baseUrl() ?>/company/buildings?_parent=<?= $this->companyId ?>"></div>
							</div>
						</div>

					</div>

				</div>
				<div role="tabpanel" class="tab-pane" id="owner_employees_tab">

					<div class="content-box">
						<h3 id="employees" class="content-box-header bg-primary" style="text-align: left;">
							<i class="glyph-icon icon-building"></i>
							EMPLOYEES
							<div class="header-buttons-separator">

								<a class="icon-separator" href="javascript:cmp_company_employees.showNewDialog(<?= $this->companyId ?>);">
									<i class="glyph-icon icon-plus"></i>
								</a>
								<a class="icon-separator" href="<?php echo App::baseUrl() ?>/company/excelexport?gridId=company_employees&_parent=<?= $this->companyId ?>" target='_blank'>
									<i class="glyph-icon fa-file-excel-o"></i>
								</a>
								<div class="table-maindiv">
									<input type="text" name="search-inspection" class="searchtable" id="search_employee" placeholder="Search for Employee">
									<a href="#" class="" id="searchEmployeeBtn"><i class="glyph-icon icon-search"></i></a>
								</div>

							</div>
						</h3>

						<div class="content-box-wrapper">
							<div class="row">
								<div id="owner_list_of_employees" jsId="owner_list_of_employees" dojoType="dijit.layout.ContentPane" href="<?= App::baseUrl() ?>/company/employees?_parent=<?= $this->companyId ?>"></div>
							</div>
						</div>

					</div>

				</div>


				<div role="tabpanel" class="tab-pane" id="owner_company_tab">

					<div class="content-box">
						<h3 class="content-box-header bg-primary" style="text-align: left;">
							<i class="glyph-icon icon-building"></i>
							PROFILE
						</h3>

						<div class="content-box-wrapper">
							<div class="row">
								<div id="owner_copmany_profile" dojoType="dijit.layout.ContentPane" title="Profile" href="<?= $this->baseUrl ?>/company/admin?_parent=<?= $this->companyId ?>"></div>
							</div>
						</div>

					</div>

				</div>
			</div>

		</div>

	</div>

<!--

<div dojoType="dijit.layout.BorderContainer" style="width: 100%; height: 100%;" design="headline" gutters="false">
    <div dojoType="ginger.TabContainer" region="center" style="background-color: white">
    	<div dojoType="dijit.layout.ContentPane" title="Inspections" href="<?= $this->baseUrl ?>/company/inspections?_parent=<?= $this->companyId ?>"></div>

        <div dojoType="dijit.layout.ContentPane" title="Employees" href="<?= $this->baseUrl ?>/company/employees?_parent=<?= $this->companyId ?>"></div>
        <div dojoType="dijit.layout.ContentPane" title="Profile" href="<?= $this->baseUrl ?>/company/admin?_parent=<?= $this->companyId ?>"></div>
    </div>
</div>

-->
<!-- SUBMIT DIALOG -->
<div id="dialogSubmit" dojoType="dijit.Dialog">

	<div class="content-box">

		<h3 class="content-box-header bg-primary" style="text-align: left;">
			<i class="glyph-icon icon-lock"></i>
			Lock
			<div class="header-buttons-separator">

							<!-- 	<a class="icon-separator" href="javascript:dialogSubmit.hide();">
									<i class="glyph-icon icon-remove"></i>
								</a> -->
							</div>
						</h3>

						<div class="modal-body importpopup" >
							<div class="row">
								<div class="col-sm-12" style="padding-top: 20px;">
									<label id="lblInfo"></label>
								</div>
								<div class="col-sm-12" style="padding-top: 20px;text-align: center;">

									<button dojoType="dijit.form.Button" class="short" type="submit">OK</button>

								</div>
							</div>






							
							
						</div>
					</div>

				</div>




				<script type="text/javascript">
					$(document).ready(function() {
						hideSubTable();
						$("#doors_header").click(function(e){
							e.preventDefault();
							console.log("e");
							$("#doors_header").addClass('activeT')
							$("#history_header").removeClass('activeT')
							hideSubTable()
						});

						$("#history_header").click(function(e){
							e.preventDefault();
							console.log("e");
							$("#history_header").addClass('activeT')
							$("#doors_header").removeClass('activeT')
							hideSubTable()
						});

						$("#searchInspectionBtn").click(function(e){
							searchInspection();	
						});
						$("#searchDoorBtn").click(function(e){
							searchDoor();	
						});
						$("#searchHistoryBtn").click(function(e){
							searchHistroy();	
						});



						$('#search_inspection').on('keypress', function(e) {           
							var code = e.keyCode || e.which;
							if(code==13){
								searchInspection();  
							}
						});

						$('#search_door').on('keypress', function(e) {           
							var code = e.keyCode || e.which;
							if(code==13){
								searchDoor();  
							}
						});

						$('#search_history').on('keypress', function(e) {           
							var code = e.keyCode || e.which;
							if(code==13){
								searchHistroy();  
							}
						});
						
						$("#searchBuildingBtn").click(function(e){
							searchBuilding();	
						});

						$("#searchEmployeeBtn").click(function(e){
							searchEmployee();	
						});

						$('#search_building').on('keypress', function(e) {           
							var code = e.keyCode || e.which;
							if(code==13){
								searchBuilding();  
							}
						});

						$('#search_employee').on('keypress', function(e) {           
							var code = e.keyCode || e.which;
							if(code==13){
								searchEmployee();  
							}
						});

						/*Export data*/
						$(".door-excel-export").click(function(e){
							var wpurl = $(this).attr("href")+'&_super=' + getParent();
							$(this).attr('href', wpurl);
						});

						$(".history-excel-export").click(function(e){
							var wpurl = $(this).attr("href")+'&_super=' + getParent();
							$(this).attr('href', wpurl);
						});

					});

					function searchInspection(){
						var search = $("#search_inspection").val();
						bratiliusDialog.setGrid("cmp_company_inspections");
						var _parent = getRootParent();
						var elements = {
							"_parent": _parent,
							"BUILDING":"*"+search+"*",
							"BUILDING_ADDRESS":"*"+search+"*",
							"BUILDING_OWNER":"*"+search+"*",
							"CITY":"*"+search+"*",
							"STATE":"*"+search+"*",
											// "INSPECTION_DATE":search+"*",
							// "INSPECTION_COMPLETE_DATE":search+"*",
							// "REINSPECT_DATE":search+"*",
							"INSPECTOR":"*"+search+"*",
							// "INSPECTION_COMPLETE_DATE_to": null,
							// "INSPECTION_DATE_to": null,
							// "REINSPECT_DATE_to": null,
							// 'SUMMARY': null,
							// "TEMPLATE": null,
							// column_14: search,
							// column_15: null
							'status': "*"+search+"*"
						}
						bratiliusDialog.executeSearch(elements)
					}

					function searchDoor(){

						var search = $("#search_door").val();
						bratiliusDialog.setGrid("cmp_company_doors");
						var _parent = getParent();
						var elements = {
							"_super": _parent,
							"NUMBER":search+"*",
							"compliant":"*"+search+"*",
							"LOCATION":search+"*"
						}
						bratiliusDialog.executeSearch(elements)
					}

					function searchHistroy(){

						var search = $("#search_history").val();
						bratiliusDialog.setGrid("cmp_company_history");
						var _parent = getParent();
						var elements = {
							"_super": _parent,
							"INSPECTOR_ID":search+"*",
							"INSPECTOR_ROLE":search+"*",
							"ASSIGNED_DATE":search+"*",
							"COMMENTS":"*"+search+"*"
						}
						bratiliusDialog.executeSearch(elements)
					}

					function searchBuilding(){

						var search = $("#search_building").val();
						bratiliusDialog.setGrid("cmp_company_buildings");
						var _parent = getRootParent();
						var elements = {
							"_parent": _parent,
							"NAME":"*"+search+"*",
							"INSPECTION_COMPANY":"*"+search+"*",
							"PRIMARY_CONTACT_LAST_NAME":"*"+search+"*",
							"ADDRESS_1":"*"+search+"*",
							"ADDRESS_2":"*"+search+"*",
							"CITY":"*"+search+"*",
							"STATE":"*"+search+"*",		
							"ZIP":"*"+search+"*"	
						}
						bratiliusDialog.executeSearch(elements)
					}

					function searchEmployee(){
						var search = $("#search_employee").val();
						bratiliusDialog.setGrid("cmp_company_employees");
						var _parent = getRootParent();
						var elements = {
							"_parent": _parent,
							"FIRST_NAME":"*"+search+"*",
							"LAST_NAME":"*"+search+"*",
							"EMAIL":"*"+search+"*",
							// "ADDRESS_2":"*"+search+"*",
							"CITY":"*"+search+"*",
							"STATE":"*"+search+"*"	
						}
						bratiliusDialog.executeSearch(elements)
					}

					function getParent(){

						var array = $(".content-box-wrapper #parentId")
						var _parent = -1;
						for(i=0;i< array.length;i++)
						{
							card_value =  array[i].value;
							if(array[i].value != '' ){
								_parent = array[i].value; break;   
							} 
						}

						return _parent;
					}

					function getRootParent(){

						var array = $(".content-box-wrapper #root_parentId")
						var _parent = -1;
						for(i=0;i< array.length;i++)
						{
							card_value =  array[i].value;
							if(array[i].value != '' ){
								_parent = array[i].value; break;   
							} 
						}
						return _parent;
					}


				</script>
