<div class="content-box">
	<h3 id="providers" class="content-box-header bg-primary" style="text-align: left;">
		<i class="glyph-icon icon-user-md"></i>
		INSPECTION COMPANIES
		<div class="header-buttons-separator">
			<a class="icon-separator" href="javascript:cmp_inspection_company.showNewDialog();">
				<i class="glyph-icon icon-plus"></i>
			</a>
			<a class="icon-separator" href="<?php echo App::baseUrl() ?>/inspectioncompany/excelexport?gridId=inspection_company" target='_blank'>
				<i class="glyph-icon fa-file-excel-o"></i>
			</a>
<!-- 
			<a class="icon-separator" href="javascript:bratiliusDialog.showSearch(
			'<?php //echo App::baseUrl() ?>/inspectioncompany/search?_model=inspection_company', 'cmp_inspection_company');">
			<i class="glyph-icon icon-search"></i>
		</a> -->
		<div class="table-maindiv">
			<input type="text" name="search-inspection" class="searchtable" id="search_inspection" placeholder="Search for Company" value="<?php echo nvl($this->gridParams['NAME'], '') ?>">
			<a href="#" class="" id="searchInspectionBtn"><i class="glyph-icon icon-search"></i></a>	
		</div>


	</div>
</h3>

<div class="content-box-wrapper">
	<div class="row">
		<div id="list_of_providers" jsId="list_of_providers" dojoType="dijit.layout.ContentPane" href="<?= App::baseUrl() ?>/inspectioncompany/providers">			
		</div>
	</div>
</div>
</div>
<div class="content-box">
<h3 id="provider_employees" class="content-box-header bg-primary" style="text-align: left;">
	<i class="glyph-icon icon-user-md"></i>
	EMPLOYEES
	<div class="header-buttons-separator">
		<a class="icon-separator" href="javascript:cmp_emp.showNewDialog();">
			<i class="glyph-icon icon-plus"></i>
		</a>
		<a class="icon-separator door-excel-export" href="<?php echo App::baseUrl() ?>/inspectioncompany/excelexport?gridId=emp" target='_blank'>
			<i class="glyph-icon fa-file-excel-o"></i>
		</a>
<!-- 
		<a class="icon-separator" href="javascript:bratiliusDialog.showSearch(
		'<?php //echo App::baseUrl() ?>/inspectioncompany/search?_model=emp', 'cmp_emp');">
		<i class="glyph-icon icon-search"></i>
	</a> -->
	<div class="table-maindiv">
		<input type="text" name="search-inspection" id="search_emp" class="searchtable" placeholder="Search for Employee" value="<?php echo nvl($this->gridParams['FIRST_NAME'], '') ?>">
		<a href="#" class="" id="searchEmpBtn"><i class="glyph-icon icon-search"></i></a>	
	</div>
</div>
</h3>

<div class="content-box-wrapper">
	<div class="row">
		<div id="list_of_provider_employees" jsId="list_of_provider_employees" dojoType="dijit.layout.ContentPane" href="<?= App::baseUrl() ?>/inspectioncompany/provideremployees?_super=-1">			
		</div>
	</div>
</div>

</div>




<script type="text/javascript">
	$(document).ready(function() {

		$("#searchInspectionBtn").click(function(e){
			searchInspectionCompany();	
		});

		$("#searchEmpBtn").click(function(e){
			searchInspectionCompanyEmp();	
		});


		$('#search_inspection').on('keypress', function(e) {           
			var code = e.keyCode || e.which;
			if(code==13){
				searchInspectionCompany();  
			}
		});
		$('#search_emp').on('keypress', function(e) {           
			var code = e.keyCode || e.which;
			if(code==13){
				searchInspectionCompanyEmp();  
			}
		});

		/*Export data*/
		$(".door-excel-export").click(function(e){
			var wpurl = $(this).attr("href")+'&_super=' + getParent();
			$(this).attr('href', wpurl);
		});


	});


	function searchInspectionCompany(){
		var search = $("#search_inspection").val();
		bratiliusDialog.setGrid("cmp_inspection_company");
		var elements = {
			"NAME":"*"+search+"*",
			"PRIMARY_CONTACT":"*"+search+"*",
			"PRIMARY_CONTACT_PHONE":"*"+search+"*",
			"ADDRESS_1":"*"+search+"*",
			"CITY":"*"+search+"*",
			"country":"*"+search+"*",
			"STATE":"*"+search+"*"		
		}
		bratiliusDialog.executeSearch(elements)
	}

	function searchInspectionCompanyEmp(){
		var search = $("#search_emp").val();
		var _parent = getParent();
		bratiliusDialog.setGrid("cmp_emp");
		var elements = {
			"_super": _parent,
			"FIRST_NAME":"*"+search+"*",
			"LAST_NAME":"*"+search+"*",
			"EMAIL":"*"+search+"*",
			// "ADDRESS_2":"*"+search+"*",
			"CITY":"*"+search+"*",
			"STATE":"*"+search+"*"		
		}
		
		bratiliusDialog.executeSearch(elements)
	}

	function getParent(){

		var array = $(".content-box-wrapper #parentId")
		var _parent = -1;
		for(i=0;i< array.length;i++)
		{
			card_value =  array[i].value;
			if(array[i].value != '' ){
				_parent = array[i].value; break;   
			} 
		}

		return _parent;
	}

</script>