<div class="content-box">
	<h3 id="inspections" class="content-box-header bg-primary" style="text-align: left;">
		<i class="fa fa-edit"></i>
		INSPECTIONS
		<div class="header-buttons-separator">
			<a class="icon-separator" href="javascript:cmp_inspection.showNewDialog();">
				<i class="glyph-icon icon-plus"></i>
            </a>
			<a class="icon-separator" href="javascript:bratiliusDialog.showSearch(
				'<?php echo App::baseUrl() ?>/inspection/search?_model=inspection', 'cmp_inspection');">
				<i class="glyph-icon icon-search"></i>
            </a>

			
		</div>
	</h3>
	
	<div class="content-box-wrapper">
		<div class="row">
			<div id="list_of_inspections" jsId="list_of_inspections" dojoType="dijit.layout.ContentPane" href="<?= App::baseUrl() ?>/inspection/inspections"></div>
		</div>
	</div>
	
</div>

<!-- <div class="example-box-wrapper"> -->

	<!-- <ul class="nav nav-tabs">
		<li class="active"><a href="#inspection_doors_tab" aria-controls="inspection_doors_tab" role="tab" data-toggle="tab">Doors</a></li>
		<li><a href="#inspection_history_tab" aria-controls="inspection_history_tab" role="tab" data-toggle="tab">History</a></li>
	</ul> -->

	<!-- Tab panes -->
<!--   <div class="tab-content"> -->
  	
  	<!-- Door Tab Start -->
    <div role="tabpanel" class="tab-pane active" id="inspection_tab">
    	<div class="content-box">
			<h3  class="content-box-header bg-primary" style="text-align: left;">
			 <a class="activeT" id="doors_header" href="#"><i class="fa fa-columns"></i>
				DOORS</a>
			 <a href="#" id="history_header" style="text-align: left;">
				<i class="glyph-icon icon-history"></i>
				HISTORY
             </a>
             <!--Doors-->   	
				<div style="display: inline-block;"><div class="header-buttons-separator door-header">
					<a class="icon-separator" href="javascript:cmp_inspection_door.showNewDialog();">
						<i class="glyph-icon icon-plus"></i>
		            </a>
					<a class="icon-separator" href="javascript:bratiliusDialog.showSearch(
						'<?php echo App::baseUrl() ?>/inspection/search?_model=inspection_door', 'cmp_inspection_door');">
						<i class="glyph-icon icon-search"></i>
		            </a>
			
				</div>
             <!--histroy-->
             <div class="header-buttons-separator histroy-header" hidden>
					<a class="icon-separator" href="javascript:bratiliusDialog.showSearch(
						'<?php echo App::baseUrl() ?>/inspection/search?_model=inspection_inspects', 'cmp_inspection_inspects');">
						<i class="glyph-icon icon-search"></i>
		            </a>
				</div>
             </div>
			</h3>
			
		
			
		<!-- </div>
	</div> -->
	<!-- Door Tab End -->
	
	<!-- History Tab Start -->
  <!--   <div role="tabpanel" class="tab-pane active" id="inspection_history_tab"> -->
    	
    	<!-- <div class="content-box"> -->
			
				
			
<!--Doors--> 
		  <div class="content-box-wrapper door-detail">
				<div class="row">
					<div id="list_of_doors" jsId="list_of_doors" dojoType="dijit.layout.ContentPane" href="<?= App::baseUrl() ?>/inspection/doors?_super=-1"></div>
				</div>
			</div>
			  <!--histroy-->
			<div class="content-box-wrapper histroy-detail" hidden>
				<div class="row">
					<div id="list_of_changes" jsId="list_of_doors" dojoType="dijit.layout.ContentPane" href="<?= App::baseUrl() ?>/inspection/changes?_super=-1"></div>
				</div>
			</div>
			
	<!-- 	</div> -->
    	
<!--     </div>History Tab End -->
    
    
  </div>
        
</div>

<? 
/*
//function assignInspection() is located in InspectionGrid.js ?>
<div dojoType="dijit.layout.BorderContainer" style="width: 100%; height: 90%;" design="headline" liveSplitters="false">
    <div dojoType='custom.ContentPane' region='top' splitter='true'
		 style="height: 60%; width: 100%;">
     	<?= $this->partial("../widgets/bratiliusgrid.phtml", 
		                   array("grid" 		=> $this->components['inspection'],
        	                     "can"  		=> $this->access['inspection'],
								 "caption"      => 'INSPECTIONS',
								 "customGrid"   => 'custom.InspectionGrid',
		                         "caption_singular" => "INSPECTION",
		                   		 'dialog'       => 'gridDialogInspection',
		                   		 "detailedView"	=> $this->baseUrl . "/inspection/inspection",
		                   		 "imageNew"	 	=> $this->baseUrl . "/public/images/New Inspection.png")) ?>
	</div>
	         
	<div dojoType="ginger.TabContainer" region="center" style="width: 100%;">
		<div dojoType="custom.ContentPane" title="Doors">
      		<?= $this->partial( "../widgets/bratiliusgrid.phtml",
				        	    array("grid" 		 => $this->components['inspection_door'], 
				        	          'can'  	 	 => $this->access['inspection_door'],
									  'caption' 	 => 'DOORS',
				        	          "caption_singular" => "DOOR",
									  'dialog'       => 'gridDialogDoor',
									  "detailedView" => $this->baseUrl . "/inspection/door",
				        	    	  'searchView'	 => $this->baseUrl . "/inspection/doorsearch",
				        	    	  "imageNew"	 => $this->baseUrl . "/public/images/New Door.png")) ?>
    	</div>
    	<div dojoType="custom.ContentPane" title="History">
      		<?= $this->partial( "../widgets/bratiliusgrid.phtml",
        	    array("grid"  	=> $this->components['inspection_inspects'], 
        	          "can"   	=> $this->access['inspection_inspects'],
        	    	  "caption" => "HISTORY",
        	    	  "icons" 	=> array("search"=>true, "excel"=>true)
        	    )) ?>
    	</div>
    	<div dojoType="custom.ContentPane" title="Photobucket">
      		<?= $this->partial( "../widgets/bratiliusgrid.phtml",
        	    array("grid"  		 => $this->components['inspection_photobucket'], 
        	          "caption" 	 => "PHOTOBUCKET",
        	    	  "customGrid"   => 'custom.PhotobucketGrid',
		              "detailedView" => $this->baseUrl . "/inspection/photobucket",
        	    	  "icons"		 => array('new' => true, 'search' => true, 'excel' => true, 'download' => true),
        	    	  "imageNew"	 => $this->baseUrl . "/public/images/New Photobucket.png" 
        	    	)) 
        	?>
    	</div>
 	</div>
</div>
 * 
 * */
 ?>
 

<!-- SUBMIT DIALOG -->
<div id="dialogSubmit" dojoType="dijit.Dialog">

   <div class="content-box">
	
	<h3 class="content-box-header bg-primary" style="text-align: left;">
		<i class="glyph-icon icon-lock"></i>
		Lock
		<div class="header-buttons-separator">

		<!-- 	<a class="icon-separator" href="javascript:dialogSubmit.hide();">
				<i class="glyph-icon icon-remove"></i>
			</a> -->
		</div>
	</h3>

	<div class="modal-body importpopup" >
                <div class="row">
					<div class="col-sm-12" style="padding-top: 20px;">
					   <label id="lblInfo"></label>
					</div>
					<div class="col-sm-12" style="padding-top: 20px;text-align: center;">
					
                       <button dojoType="dijit.form.Button" class="short" type="submit">OK</button>

					</div>
	</div>
				
				
				
				
				

		
		
	</div>
</div>

</div>
<script type="text/javascript">
	$(document).ready(function() {
		hideSubTable();
		$("#doors_header").click(function(e){
			e.preventDefault();
			console.log("e");
			$("#doors_header").addClass('activeT')
			$("#history_header").removeClass('activeT')
			hideSubTable()
		});

		$("#history_header").click(function(e){
			e.preventDefault();
			console.log("e");
			$("#history_header").addClass('activeT')
			$("#doors_header").removeClass('activeT')
			hideSubTable()
		});


		
		
	});

function hideSubTable(){

	if($("#doors_header").hasClass('activeT')){

			$(".door-header").show();
			$(".door-detail").show();
			$(".histroy-header").hide();
			$(".histroy-detail").hide();
		}else{
			$(".histroy-header").show();
			$(".histroy-detail").show();
			$(".door-header").hide();
			$(".door-detail").hide();
		}
}

</script>

 
