<div dojoType="dijit.layout.BorderContainer" style="width: 100%; height: 100%;" design="sidebar">
    <div dojoType='dijit.layout.ContentPane' region='left' splitter='true' style="width: 25%">
        <?= $this->partial( "../widgets/dojotree.phtml",
                            array("id" => 'roles')); ?>
    </div>
    <div dojoType="dijit.layout.ContentPane" region='top' splitter='true'
         style="background-color: white; height: 50%">
        <?= $this->partial( "../widgets/bratiliusgrid.phtml",
                            array( "grid" => $this->components['users'], "can" => $this->access['users'])); ?>
    
    </div>
    <div dojoType="dijit.layout.ContentPane" region="center" style="background-color: white">
        <?= $this->partial( "../widgets/bratiliusgrid.phtml",
                            array( "grid" => $this->components['user_roles'], "can" => $this->access['user_roles'])); ?>
    
    </div>
</div>