<?php
 $id = $this->grid->getId();
 $rows = $this->grid->fetchPage($this->gridParams);
 $pageCount = $rows->getPages()->pageCount;
?>

 <div dojoType="<?php echo $this->customGrid ? $this->customGrid : 'custom.widgets.BratiliusGrid' ?>" id="cmp_<?php echo $this->grid->getId() ?>"
	 jsId="cmp_<?php echo $this->grid->getId() ?>" detailedView = "<?php echo $this->detailedView ?>" parentPaneId='<?php echo $this->parentPaneId ?>'
	 formActionUrl = "<?php echo $this->formActionUrl ?>">
	<div class="table table-striped table-bordered" id="cmp_<?php echo $this->grid->getId() ?>_table">
		
		
			<div class="row gridHeader">
			<?php if ($this->gridParams['selectAll']): ?>
				<div class="col-md-1 columnHeader" style="cursor: pointer;"><input type="checkbox" dojoType="dijit.form.CheckBox" id="cmp_<?php echo $this->grid->getId() ?>_select_all"/></div>
			<?php endif; ?>
		<?php  foreach ($this->grid->getColumns() as $columnId => $column): 
				$view = $column->getView();
				if ($column->getVisible(Data_Column_Grid::GRID)): ?>
					<?php // figure out the new sort direction, if this column is already being sorted 
					//Zend_Registry::get('logger')->info('Column: ' . $columnId . ' sortBy: ' . $this->gridParams['sortBy'] . ', direction: ' . $this->gridParams['sortDirection']);
					$newSortDirection = $columnId == $this->gridParams['sortBy'] ? ($this->gridParams['sortDirection'] ? 0: 1) : 1; 
					$sortClass = ($columnId === $this->gridParams['sortBy']) ? ($this->gridParams['sortDirection'] ? 'icon-sort-down' : 'icon-sort-up') : 'icon-unsorted'; ?>
					 
					<div class="col-md-<?= $column->getSize() ?> columnHeader" style="cursor: pointer;" onclick="cmp_<?php echo $this->grid->getId() ?>.sortByColumn('<?php echo $column->getId() ?>', <?php echo $newSortDirection ?>)">
						<?php echo $column->getTitle() ?> <i class="glyph-icon <?php echo $sortClass ?>"></i>
					</div>
				<?php endif;	
			 endforeach; ?>
			</div>
		
		
		
		<?php 
		$i = 1;
		foreach ($rows as $row): ?>
		<div class="row gridRow <?php echo ($i == 1) ? 'odd gradeA' : 'even gradeA'?>">
		<?php if ($this->gridParams['selectAll']): ?>
			<div class="col-md-1 columnCell"><input type="checkbox" dojoType="dijit.form.CheckBox" id="cmp_<?php echo $this->grid->getId() ?>_<?php echo $row['id'] ?>"/></div>
		<?php endif; ?>
			<?php 
			foreach ($this->grid->getColumns() as $columnId => $column): 
				if (!$column->getVisible(Data_Column_Grid::GRID)): continue; endif; //if column is not visible, do not print the cell;
				if ($column->isCalculated()): ?><div class="col-md-<?= $column->getSize() ?> columnCell"><?php echo $column->calculate($row) ?></div><?php	continue; endif; //if this is a calculated column, call the calculation as defined in the grid
				
				//otherwise just print the contents in the appropriate place in the table
				foreach ($row as $cellId => $cell):
					if ($columnId == $cellId): ?><div class="col-md-<?= $column->getSize() ?> columnCell"><?php echo $cell ?>&nbsp;</div><?php continue; endif;
			 	endforeach;
			 endforeach; ?>
		</div>
		<?php 	 
                $i = ($i == 1) ? 2 : 1; //this is for odd and even rows styling
		endforeach; ?>
		
	</div>
</div>

<?php if ($this->gridParams['selectAll']): ?>
	<div style="text-align: left;">
		<div dojoType="dijit.form.Button" class="short" onclick="cmp_<?php echo $this->grid->getId() ?>.deleteItems();"><?php echo trans('Delete') ?></div>
	</div>
<?php endif; ?>


<?php if ($this->grid->getUsePaginator()): ?>
<div dojoType="custom.widgets.BratiliusGridPaginator" id="cmp_<?php echo $id ?>_paginator" jsid="cmp_<?php echo $id ?>_paginator"
	 pageCount="<?php echo $pageCount?>"  grid="cmp_<?php echo $id ?>" curPageIndex="<?php echo nvl($this->gridParams['page'], '0') ?>"></div>	
<?php endif; ?>