<? 
	$left = $this->left ? 'left: ' . $this->left . ';' : ''; 
	$top  = $this->top	? 'top: ' . $this->top . ';' : '';
?>
<!-- Disclaimers -->
<div style="position: absolute; <?= $top ?><?= $left ?> height: 36px; font-size: 8pt; text-align: right">
	COPYRIGHT 2009-<?= date('Y') ?> DOORDATA Solutions, Inc., ALL RIGHTS RESERVED.<br>
	Use of this inspection form without the express written consent of DOORDATA Solutions, Inc. is strictly forbidden.
</div>
