<?
$user = Zend_Auth::getInstance()->getIdentity();
?>

<div class="row">
  <div class="col-lg-12">

    <? if($user == 'admin'): ?>
      <a href="javascript: showUploadVideoDialog()">
        <button type="button" class="btn btn-info1 btn-lg pull-right" data-toggle="modal" data-target="#myModal" style="margin-right: 32px;">Upload Video</button></div></div>
      </a>
    <? endif; ?>

    <div class="demo-gallery">
      <ul id="lightgallery">

       <? foreach ($this->videoList as $key => $value): ?>

        <li class="video col-lg-4 col-md-4 col-sm-12 col-xs-12 rm_<?= $value['ID']?>" data-html="#video2">

          <video width="90%" height="290" controls>
            <source src="<? echo $this->baseUrl().'/public/help/video/'.$value['videoUrl']; ?>" type="video/mp4">
            </video>

            <h4>
              <?= $value['title'] ?>
              
            </h4>
            <p><?= $value['description'] ?></p>
            <? if($user == 'admin'): ?>
             <ul class="sameline">
               <li> 
                <i class="fa icon-remove" style="color:red;" onclick="removeGallery(<?= $value['ID']?>)"> </i>
              </li>
              <li> 
               <? if($user == 'admin'): ?>
                <input type="number" maxlength="2" id="sorder" onchange="sorder(event,<?= $value['ID']?>)" value="<?= $value['sorder']?>" style="width:30%;">
              <? endif; ?>
            </li>
          </ul>
        <? endif; ?>
        <? if($user == 'admin'): ?>
          <p class="videopoststatus">
            <input type="checkbox" id="test<?= $value['ID']?>" onclick="enableView(event,<?= $value['ID']?>)" <? echo ($value['status']) ? 'checked':''; ?>  />
            <label for="test<?= $value['ID']?>"></label>
          </p>
        <? endif; ?>

      </li>

    <? endforeach; ?>

  </ul>

</div>


<script type="text/javascript">

//  $(document).ready(function() {
//   $('#lightgallery').lightGallery();
// });

</script>

<style>
  body {
    background-color: #152836;
    color: #eee;
    font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif
  }
  .videopoststatus{    position: absolute;
    top: 0;
    left: 12px;
    margin-top: 0 !IMPORTANT;}
    .small {
      font-size: 11px;
      color: #999;
      display: block;
      margin-top: -10px
    }

    .cont {
      text-align: center;
    }

    .page-head {
      padding: 60px 0;
      text-align: center;
    }

    .page-head .lead {
      font-size: 18px;
      font-weight: 400;
      line-height: 1.4;
      margin-bottom: 50px;
      margin-top: 0;
    }

    .btn {
      -moz-user-select: none;
      background-image: none;
      border: 1px solid transparent;
      border-radius: 2px;
      cursor: pointer;
      display: inline-block;
      font-size: 14px;
      font-weight: normal;
      line-height: 1.42857;
      margin-bottom: 0;
      padding: 6px 12px;
      text-align: center;
      vertical-align: middle;
      white-space: nowrap;
      text-decoration: none;
    }

    .btn-lg {
      border-radius: 2px;
      font-size: 18px;
      line-height: 1.33333;
      padding: 10px 16px;
    }

    .btn-primary:hover {
      background-color: #fff;
      color: #152836;
    }

    .btn-primary {
      background-color: #152836;
      border-color: #0e1a24;
      color: #ffffff;
    }

    .btn-primary {
      border-color: #eeeeee;
      color: #eeeeee;
      transition: color 0.1s ease 0s, background-color 0.15s ease 0s;
    }

    .page-head h1 {
      font-size: 42px;
      margin: 0 0 20px;
      color: #FFF;
      position: relative;
      display: inline-block;
    }

    .page-head h1 .version {
      bottom: 0;
      color: #ddd;
      font-size: 11px;
      font-style: italic;
      position: absolute;
      width: 58px;
      right: -58px;
    }

    .demo-gallery > ul {
      margin-bottom: 0;
      padding-left: 15px;
    }

    .demo-gallery > ul > li {
      margin-bottom: 15px;
      /* width: 180px;*/
      display: inline-block;
      /*margin-right: 15px;*/
      list-style: outside none none;
      height: 420px;
    }

    .demo-gallery > ul > li a {
      border: 3px solid #FFF;
      border-radius: 3px;
      display: block;
      overflow: hidden;
      position: relative;
      float: left;
    }

    .demo-gallery > ul > li a > img {
      -webkit-transition: -webkit-transform 0.15s ease 0s;
      -moz-transition: -moz-transform 0.15s ease 0s;
      -o-transition: -o-transform 0.15s ease 0s;
      transition: transform 0.15s ease 0s;
      -webkit-transform: scale3d(1, 1, 1);
      transform: scale3d(1, 1, 1);
      height: 100%;
      width: 100%;
    }

    .demo-gallery > ul > li a:hover > img {
      -webkit-transform: scale3d(1.1, 1.1, 1.1);
      transform: scale3d(1.1, 1.1, 1.1);
    }

    .demo-gallery > ul > li a:hover .demo-gallery-poster > img {
      opacity: 1;
    }

    .demo-gallery > ul > li a .demo-gallery-poster {
      background-color: rgba(0, 0, 0, 0.1);
      bottom: 0;
      left: 0;
      position: absolute;
      right: 0;
      top: 0;
      -webkit-transition: background-color 0.15s ease 0s;
      -o-transition: background-color 0.15s ease 0s;
      transition: background-color 0.15s ease 0s;
    }

    .demo-gallery > ul > li a .demo-gallery-poster > img {
      left: 50%;
      margin-left: -10px;
      margin-top: -10px;
      opacity: 0;
      position: absolute;
      top: 50%;
      -webkit-transition: opacity 0.3s ease 0s;
      -o-transition: opacity 0.3s ease 0s;
      transition: opacity 0.3s ease 0s;
    }

    .demo-gallery > ul > li a:hover .demo-gallery-poster {
      background-color: rgba(0, 0, 0, 0.5);
    }

    .demo-gallery .justified-gallery > a > img {
      -webkit-transition: -webkit-transform 0.15s ease 0s;
      -moz-transition: -moz-transform 0.15s ease 0s;
      -o-transition: -o-transform 0.15s ease 0s;
      transition: transform 0.15s ease 0s;
      -webkit-transform: scale3d(1, 1, 1);
      transform: scale3d(1, 1, 1);
      height: 100%;
      width: 100%;
    }

    .demo-gallery .justified-gallery > a:hover > img {
      -webkit-transform: scale3d(1.1, 1.1, 1.1);
      transform: scale3d(1.1, 1.1, 1.1);
    }

    .demo-gallery .justified-gallery > a:hover .demo-gallery-poster > img {
      opacity: 1;
    }

    .demo-gallery .justified-gallery > a .demo-gallery-poster {
      background-color: rgba(0, 0, 0, 0.1);
      bottom: 0;
      left: 0;
      position: absolute;
      right: 0;
      top: 0;
      -webkit-transition: background-color 0.15s ease 0s;
      -o-transition: background-color 0.15s ease 0s;
      transition: background-color 0.15s ease 0s;
    }

    .demo-gallery .justified-gallery > a .demo-gallery-poster > img {
      left: 50%;
      margin-left: -10px;
      margin-top: -10px;
      opacity: 0;
      position: absolute;
      top: 50%;
      -webkit-transition: opacity 0.3s ease 0s;
      -o-transition: opacity 0.3s ease 0s;
      transition: opacity 0.3s ease 0s;
    }

    .demo-gallery .justified-gallery > a:hover .demo-gallery-poster {
      background-color: rgba(0, 0, 0, 0.5);
    }

    .demo-gallery .video .demo-gallery-poster img {
      height: 48px;
      margin-left: -24px;
      margin-top: -24px;
      opacity: 0.8;
      width: 48px;
    }

    .demo-gallery.dark > ul > li a {
      border: 3px solid #04070a;
    }

    #lightgallery h4{
      margin-top: 0.5em;
    }

    #lightgallery p{
      margin-top: 0.5em;
    }
    .btn-info1{
     border-color: #7fa3c8 !important;
     background: #7fa3c8;
     color: #fff;
   }
   /* Base for label styling */
   [type="checkbox"]:not(:checked),
   [type="checkbox"]:checked {
    position: absolute;
    left: -9999px;
  }
  [type="checkbox"]:not(:checked) + label,
  [type="checkbox"]:checked + label {
    position: relative;
    padding-left: 1.95em;
    cursor: pointer;
  }

  /* checkbox aspect */
  [type="checkbox"]:not(:checked) + label:before,
  [type="checkbox"]:checked + label:before {
    content: '';
    position: absolute;
    left: 0; top: 0;
    width: 1.25em; height: 1.25em;
    border: 2px solid #ccc;
    background: #fff;
    border-radius: 4px;
    box-shadow: inset 0 1px 3px rgba(0,0,0,.1);
  }
  /* checked mark aspect */
  [type="checkbox"]:not(:checked) + label:after,
  [type="checkbox"]:checked + label:after {
    content: '\2713\0020';
    position: absolute;
    top: .15em; left: 0.15em;
    font-size: 1.3em;
    line-height: 0.8;
    color: #09ad7e;
    transition: all .2s;
    font-family: 'Lucida Sans Unicode', 'Arial Unicode MS', Arial;
  }
  /* checked mark aspect changes */
  [type="checkbox"]:not(:checked) + label:after {
    opacity: 0;
    transform: scale(0);
  }
  [type="checkbox"]:checked + label:after {
    opacity: 1;
    transform: scale(1);
  }
  /* disabled checkbox */
  [type="checkbox"]:disabled:not(:checked) + label:before,
  [type="checkbox"]:disabled:checked + label:before {
    box-shadow: none;
    border-color: #bbb;
    background-color: #ddd;
  }
  [type="checkbox"]:disabled:checked + label:after {
    color: #999;
  }
  [type="checkbox"]:disabled + label {
    color: #aaa;
  }
  /* accessibility */
  [type="checkbox"]:checked:focus + label:before,
  [type="checkbox"]:not(:checked):focus + label:before {
    border: 2px solid #ccccccc;
  }

  /* hover style just for information */
  label:hover:before {
    border: 2px solid #ccc!important;
  }
  .sameline {
    list-style: none;
    padding: 0;
    width:90%;
  }
  .sameline li{
   display: inline-block;
   width: 49%;
 }
 .sameline li:last-child{
   text-align: right;
 }
</style>

<script type="text/javascript">
  function showUploadVideoDialog(){
    var append = "/help/videoupload";
    var url = baseUrl + append ; 
    bratiliusDialog.frame.attr('href', url);
    // bratiliusDialog.parentPane = this.parentPane;
    bratiliusDialog.show();
    // this.scrollToTop();
  }

  function removeGallery(id){

    $.ajax({
      url: 'help/deletehelp?id='+id,
      type: "GET",
      dataType: "html",
      beforeSend: function(){
      },  
      success: function(html) {
        $('.rm_'+id).remove();
      }
    });

  }

  function enableView(event, id){

    var status = (event.target.checked)? 1:0; 

    $.ajax({
      url: 'help/enablevideo?id='+id+'&status='+status,
      type: "GET",
      dataType: "html",
      beforeSend: function(){
      },  
      success: function(html) {
        // $('.rm_'+id).remove();
      }
    });

  }

  function sorder(event,id){
   var order = event.target.value; 
   $.ajax({
    url: 'help/sordervideo?id='+id+'&order='+order,
    type: "GET",
    dataType: "html",
    beforeSend: function(){
    },  
    success: function(html) {
        // $('.rm_'+id).remove();
      }
    });
 };

 


</script>