<!-- inspections grid -->
<div dojoType="dijit.layout.ContentPane" region="center" style="overflow: hidden;">	
	<?= $this->partial("../widgets/bratiliusgrid.phtml", 
		array(
			"grid" 		=> $this->grid,
        	"can"  		=> $this->access['building_inspection'],
			"caption"      => 'INSPECTIONS: ' . $this->buildingName,
		    "caption_singular" => "INSPECTION",
		    "customGrid"   => 'custom.InspectionGrid',
		    'dialog'       => 'gridDialogInspection',
		    "searchView"	=> $this->baseUrl . "/building/search?_model=building_inspection&_super=" . $this->buildingId,
		    "detailedView"	=> "/building/inspection",
		    "imageNew"	 	=> $this->baseUrl . "/public/images/New Inspection.png",
			'parentPaneId'		=> "list_of_building_inspections",
		 	'gridParams'		=> $this->gridParams,
		 	'formActionUrl' => $this->baseUrl . '/building/save?_model=' . $this->grid->getId(),
		 	'childGridIds'		=> array('cmp_building_inspection_door','cmp_building_inspection_history'),  
		)) 
	?>
</div>