
<!-- doors grid -->
<div dojoType="dijit.layout.ContentPane" region="center" style="overflow: hidden;">
<?= $this->partial( "../widgets/bratiliusgrid.phtml",
	array(
		"grid"  	=> $this->components['building_inspection_history'], 
		"can"   	=> $this->access['building_inspection_history'],
		'caption' 	 		=> 'HISTORY',
		"caption_singular" 	=> "HISTORY",
		'dialog'       		=> 'gridDialogDoor',
		"detailedView" 		=> "/building/change",
		//'searchView'	 	=> $this->baseUrl . "/company/doorsearch",
		//"imageNew"	 		=> $this->baseUrl . "/public/images/New Door.png",
		'parentPaneId'		=> "building_list_of_doors_history",
		'gridParams'		=> $this->gridParams,
		'superGridId'		=> 'cmp_building_inspection'
		
	))
?>
</div>


