


<div class="content-box">
	<h3 id="buildings" class="content-box-header bg-primary" style="text-align: left;">
		<i class="glyph-icon icon-building"></i>
		BUILDINGS
		<div class="header-buttons-separator">
			<a class="icon-separator" href="javascript:cmp_building.showNewDialog();">
				<i class="glyph-icon icon-plus"></i>
            </a>

            <a class="icon-separator" href="<?php echo App::baseUrl() ?>/building/excelexport?gridId=building" target='_blank'>
				<i class="glyph-icon fa-file-excel-o"></i>
			</a>

			<!-- <a class="icon-separator" href="javascript:bratiliusDialog.showSearch(
				'<?php //echo App::baseUrl() ?>/building/search?_model=building', 'cmp_building');">
				<i class="glyph-icon icon-search"></i>
            </a> -->
            <div class="table-maindiv">   
            <input type="text" name="search-inspection" class="searchtable" id="search_inspection" placeholder="Search for Building" >
			<a href="#" class="" id="searchInspectionBtn"><i class="glyph-icon icon-search"></i></a>	
            </div>
			
		</div>
	</h3>
	
	<div class="content-box-wrapper">
		<div class="row">
			<div id="list_of_buildings" jsId="list_of_buildings" dojoType="dijit.layout.ContentPane" href="<?= App::baseUrl() ?>/building/buildings"></div>
		</div>
	</div>
	
</div>


<script type="text/javascript">
	$(document).ready(function() {

		$("#searchInspectionBtn").click(function(e){
			searchInspection();	
		});

		$('#search_inspection').on('keypress', function(e) {           
			var code = e.keyCode || e.which;
			if(code==13){
				searchInspection();  
			}
		});

	});


	function searchInspection(){
		var search = $("#search_inspection").val();
		bratiliusDialog.setGrid("cmp_building");
		var elements = {
			"NAME":"*"+search+"*",
			"INSPECTION_COMPANY":"*"+search+"*",
			"PRIMARY_CONTACT_LAST_NAME":"*"+search+"*",
			"ADDRESS_1":"*"+search+"*",
			"ADDRESS_2":"*"+search+"*",
			"CITY":"*"+search+"*",
			"STATE":"*"+search+"*",		
			"ZIP":"*"+search+"*"		
		}
		
		bratiliusDialog.executeSearch(elements)
	}

</script>