<?= $this->doctype() ?>
<?
$baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
//this is whether or not dojo should be built before use
$debug = Zend_Registry::get('configuration')->debug->dojo_debug_mode;
$dojoDir = $debug ? "{$baseUrl}/public/scripts/dojo" : "{$baseUrl}/public/scripts/dojo/release/dojo";

// onMobile is true if user is on the mobile device; onMobile is false if user is using other type of a client
$view = new Zend_View();
$userAgent = $view->userAgent(); 
$userAgent->getDevice();
$view = null;
$onMobile = $userAgent->getBrowserType() == 'mobile' ? true : false;
		
?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>  
		<!--  <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7"/> -->
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
		<title>Online DOORDATA</title>

		<!-- favicon -->
		<link rel="shortcut icon" href="<?= $baseUrl ?>/public/images/favicon.png">
        <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.6.11/css/lightgallery.min.css">

    <!-- JS Core -->
    <script type="text/javascript" src="<?= $baseUrl ?>/public/scripts/assets-minified/js-core.js"></script>



	<script type="text/javascript" src="<?= $baseUrl ?>/public/scripts/library/jquery-3.1.1.min.js"></script>
	<script type="text/javascript" src="<?= $baseUrl ?>/public/scripts/assets-minified/widgets/tabs/tabs.js"></script>
	<script type="text/javascript" src="<?= $baseUrl ?>/public/scripts/assets-minified/widgets/dropdown/dropdown.js"></script>

	<script type="text/javascript" src="https://cdn.jsdelivr.net/picturefill/2.3.1/picturefill.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-mousewheel/3.1.13/jquery.mousewheel.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.6.11/js/lightgallery-all.min.js"></script>
	<script type="text/javascript" src="https://f.vimeocdn.com/js/froogaloop2.min.js"></script>
	<script src="https://use.fontawesome.com/057b889565.js"></script>

		<!-- plugins -->
		<script src="<?= $dojoDir ?>/ginger/common.js" type="text/javascript"></script>
		
		<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/shell.js"></script>


		<script>
			baseUrl = '<?= $baseUrl ?>';
			dojoDir = '<?= $dojoDir ?>';
			onMobile = '<?php echo $userAgent->getBrowserType() == 'mobile' ? true : false ?>';
		</script>

		<!-- dojo bootstrap -->
		<script type="text/javascript">
			djConfig={
				parseOnLoad: true,
				gfxRenderer: "svg,silverlight,vml", // svg is first priority - this is needed for charts
				isDebug: false,
				debugAtAllCosts: false,
				dojoBlankHtmlUrl: baseUrl + '/public',
				baseUrl: './<?= $baseUrl ?>',
				modulePaths: {
					"ginger": dojoDir + '/ginger',
					"custom": dojoDir + '/custom'
				},
				preventBackButtonFix: false,
				dojoIframeHistoryUrl: baseUrl + '/public/iframe_history.html'
			};
		</script>

		<script src="https://ajax.googleapis.com/ajax/libs/dojo/1.6.2/dojo/dojo.<?= $debug ? 'xd.' : '' ?>js" type="text/javascript"></script>

		<script type="text/javascript">
			dojo.require("ginger.Loader");
			dojo.require("custom.Loader");
		</script>

		<!-- initialize back button -->
		<script type="text/javascript">
			var url = '/';
			var state = {
				back: function() {changeBody(url, true);},
				forward: function() {changeBody(url, true);},
				changeUrl: false
			};
			dojo.addOnLoad(function(){
				dojo.back.setInitialState(state);
			});     
		</script>
	</head> 
	
<body class="frontend-layout sidebar-collapsed">

		<!-- Detailed Dialog for grids -->
		<div dojoType="custom.widgets.BratiliusDialog" id="bratiliusDialog" jsid="bratiliusDialog" title=""
			 style='display: none'>
			<div dojoType="dojox.layout.ContentPane" id="bratiliusDialogFrame" jsid="bratiliusDialogFrame">
			</div>
		</div>

		<!-- Login Dialog -->
		<div dojoType="custom.LoginDialog" id="loginDialog" jsid="loginDialog" title="" 
			 style="display: none">
			<div dojoType="dojox.layout.ContentPane" id="loginDialogFrame" jsid="loginDialogFrame"
				 href="<?= $baseUrl ?>/auth/logindialog">
			</div>
		</div>

		<!-- dialog frame -->
		<div dojoType="ginger.Dialog" id="mainDialog" jsid="mainDialog" title="" draggable="false" style='display: none'>
			<div dojoType="dojox.layout.ContentPane" id="mainDialogFrame" jsid="mainDialogFrame"></div> 
		</div>

		<!-- DOOR DIALOG -->
		<div dojoType="custom.DoorDialog" class="door" jsid="gridDialogDoor" id="gridDialogDoor" style="display: none">
			<div dojoType="dojox.layout.ContentPane" jsid="gridDialogDoorFrame" id="gridDialogDoorFrame"></div>
		</div>

		<!-- INSPECTION DIALOG -->
		<div dojoType="custom.InspectionDialog" class="door" jsid="gridDialogInspection" id="gridDialogInspection" style="display: none">
			<div dojoType="dojox.layout.ContentPane" jsid="gridDialogInspectionFrame" id="gridDialogInspectionFrame"></div>
		</div>

		<!-- content -->
		<div dojoType="dojox.layout.ContentPane" class="mainDiv" align="center" id="bodyDiv" jsid="bodyDiv"
		 href="<?= $baseUrl ?>/index/home"></div>

		
		
		<!--  custom styles -->
		
		<link rel="stylesheet" type="text/css" href="<?= $dojoDir ?>/../assets-minified/all-demo.css">
		<link rel="stylesheet" type="text/css" href="<?= $dojoDir ?>/../assets-minified/icons/typicons/typicons.css">
		<link rel="stylesheet" type="text/css" href="<?= $dojoDir ?>/../assets-minified/helpers/colors.css">
		<link href="<?= $dojoDir ?>/custom/themes/desktop.css" rel="stylesheet" />
		<link rel="stylesheet" type="text/css" href="<?= $dojoDir ?>/../assets-minified/bootstrap-table/bootstrap-table.min.css">
		


		<link href="<?= $dojoDir ?>/custom/themes/custom.css" rel="stylesheet" />
		<script type="text/javascript" src="<?= $baseUrl ?>/public/scripts/assets-minified/canvas/canvasjs.min.js"></script>
		<!-- <script>(function(){var s = document.createElement("script");s.setAttribute("data-account","2EAL77I2wc");s.setAttribute("src","https://cdn.userway.org/widget.js");document.body.appendChild(s);})();</script> -->

		<!-- <script>(function(d){var s = d.createElement("script");s.setAttribute("data-account", "2EAL77I2wc");s.setAttribute("src", "https://accessibilityserver.org/widget.js");(d.body || d.head).appendChild(s);})(document)</script><noscript>Please ensure Javascript is enabled for purposes of <a href="https://accessibilityserver.org">website accessibility</a></noscript> -->
	</body>
</html>