alter table `audio` drop foreign key `audio_ibfk_7`;
alter table `building` drop foreign key `building_ibfk_2`;
alter table `building` drop foreign key `building_ibfk_3`;
alter table `building` drop foreign key `building_ibfk_4`;
alter table `building` drop foreign key `building_ibfk_5`;
alter table `company` drop FOREIGN KEY `company_ibfk_2`;
alter table `company` drop FOREIGN KEY `company_ibfk_3`;
alter table `company` drop FOREIGN KEY `company_ibfk_5`;
alter table `door` drop foreign key `door_ibfk_29`;
alter table `door` drop foreign key `door_ibfk_30`;
alter table `door` drop foreign key `door_ibfk_31`;
alter table `door` drop foreign key `door_ibfk_32`;
alter table `door` drop foreign key `door_ibfk_34`;
alter table `door` drop foreign key `door_ibfk_35`;
alter table `door` drop foreign key `door_ibfk_36`;
alter table `door` drop foreign key `door_ibfk_37`;
alter table `door` drop foreign key `door_ibfk_38`;
alter table `door` drop foreign key `door_ibfk_39`;
alter table `door` drop foreign key `door_ibfk_42`;
alter table `door` drop foreign key `door_ibfk_44`;
alter table `door` drop foreign key `door_ibfk_45`;
alter table `door` drop foreign key `door_ibfk_46`;
alter table `door` drop foreign key `door_ibfk_47`;
alter table `door` drop foreign key `door_ibfk_48`;
alter table `door` drop foreign key `door_ibfk_49`;
alter table `door` drop foreign key `door_ibfk_50`;
alter table `door` drop foreign key `door_ibfk_51`;
alter table `door` drop foreign key `door_ibfk_52`;
alter table `door` drop foreign key `door_ibfk_53`;
alter table `door` drop foreign key `door_ibfk_54`;
alter table `door` drop foreign key `door_ibfk_55`;
alter table `door` drop foreign key `door_ibfk_56`;
alter table `door` drop foreign key `door_ibfk_57`;
alter table `door` drop foreign key `door_ibfk_58`;
alter table `door` drop foreign key `door_ibfk_59`;
alter table `door` drop foreign key `door_ibfk_60`;
alter table `door` drop foreign key `door_ibfk_61`;
alter table `door` drop foreign key `door_ibfk_62`;
alter table `door` drop foreign key `door_ibfk_63`;
alter table `door` drop foreign key `door_ibfk_64`;
alter table `door` drop foreign key `door_ibfk_65`;
alter table `door` drop foreign key `door_ibfk_66`;
alter table `door` drop foreign key `door_ibfk_67`;
alter table `door` drop foreign key `door_ibfk_68`;
alter table `door` drop foreign key `door_ibfk_69`;
alter table `door` drop foreign key `door_ibfk_70`;
alter table `door` drop foreign key `door_ibfk_71`;
alter table `door` drop foreign key `door_ibfk_72`;
alter table `door` drop foreign key `door_ibfk_73`;
alter table `door` drop foreign key `door_ibfk_74`;
alter table `door` drop foreign key `door_ibfk_75`;
alter table `door` drop foreign key `door_ibfk_76`;
alter table `door` drop foreign key `door_ibfk_77`;
alter table `door` drop foreign key `door_ibfk_78`;
alter table `door` drop foreign key `door_ibfk_79`;
alter table `door` drop foreign key `door_ibfk_80`;
alter table `door` drop foreign key `door_ibfk_82`;
alter table `door` drop foreign key `door_ibfk_83`;
alter table `door` drop foreign key `door_ibfk_84`;
alter table `door` drop foreign key `door_ibfk_85`;
alter table `door` drop foreign key `door_ibfk_86`;
alter table `door` drop foreign key `door_ibfk_87`;
alter table `door` drop foreign key `door_ibfk_88`;
alter table `door` drop foreign key `door_ibfk_89`;
alter table `door_code` drop foreign key `door_code_ibfk_5`;
alter table `door_code` drop foreign key `door_code_ibfk_6`;
alter table `door_note` drop foreign key `door_note_ibfk_3`;
alter table `door_type` drop foreign key `door_type_ibfk_3`;
alter table `door_type` drop foreign key `door_type_ibfk_4`;
alter table `download` drop foreign key `download_ibfk_1`;
alter table `employee` drop foreign key `employee_ibfk_2`;
alter table `employee` drop foreign key `employee_ibfk_4`;
alter table `floorplan` drop foreign key `floorplan_ibfk_2`;
alter table `framedetail` drop foreign key `framedetail_ibfk_2`;
alter table `hardware` drop foreign key `hardware_ibfk_2`;
alter table `ink` drop foreign key `ink_ibfk_2`;
alter table `inspect` drop foreign key `inspect_ibfk_3`;
alter table `inspect` drop foreign key `inspect_ibfk_4`;
alter table `inspection` drop foreign key `inspection_ibfk_2`;
alter table `inspection` drop foreign key `inspection_ibfk_4`;
alter table `inspection` drop foreign key `inspection_ibfk_6`;
alter table `inspection` drop foreign key `inspection_ibfk_7`;
alter table `integration` drop foreign key `integration_ibfk_5`;
alter table `integration` drop foreign key `integration_ibfk_6`;
alter table `integration` drop foreign key `integration_ibfk_7`;
alter table `picture` drop foreign key `picture_ibfk_2`;
alter table `role` drop foreign key `role_ibfk_1`;
alter table `user_file` drop foreign key `user_file_ibfk_2`;
alter table `user_role` drop foreign key `user_role_ibfk_4`;

ALTER TABLE `audio` ADD FOREIGN KEY (`DOOR_ID`) REFERENCES `door` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `building` ADD FOREIGN KEY (`STATE`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `building` ADD FOREIGN KEY (`COUNTRY`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `building` ADD FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `company` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `building` ADD FOREIGN KEY (`PRIMARY_CONTACT`) REFERENCES `employee` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `company` ADD FOREIGN KEY (`STATE`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `company` ADD FOREIGN KEY (`TYPE`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `company` ADD FOREIGN KEY (`PRIMARY_CONTACT`) REFERENCES `employee` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`FIRE_RATING_2`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`FIRE_RATING_1`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`FIRE_RATING_3`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`FIRE_RATING_4`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`MATERIAL`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`ELEVATION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`FRAME_ELEVATION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`STYLE`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`TEMP_RISE`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`FRAME_MATERIAL`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`LISTING_AGENCY`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`INSPECTOR_ID`) REFERENCES `employee` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`INSPECTION_ID`) REFERENCES `inspection` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`BUILDING_ID`) REFERENCES `building` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`HANDING`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`HINGE_HEIGHT`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`HINGE_THICKNESS`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`HINGE_FRACTION1`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`HINGE_FRACTION2`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`HINGE_FRACTION3`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`HINGE_FRACTION4`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`HINGE_BACKSET`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`TOP_TO_CENTERLINE_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`STRIKE_HEIGHT`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`PREFIT_FRACTION_X`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`PREFIT_FRACTION_Y`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`FRAME_OPENING_FRACTION_X`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`FRAME_OPENING_FRACTION_Y`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`LITE_CUTOUT_FRACTION_X`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`LITE_CUTOUT_FRACTION_Y`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`LOCKSTILE_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`TOPRAIL_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`LOCK_BACKSET`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`COMPLIANT`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`A_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`B_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`C_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`D_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`E_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`F_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`G_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`H_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`I_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`J_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`K_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`L_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`M_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`N_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`O_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`P_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`Q_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`R_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`S_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`T_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`U_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door` ADD FOREIGN KEY (`V_FRACTION`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door_code` ADD FOREIGN KEY (`DOOR_ID`) REFERENCES `door` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door_code` ADD FOREIGN KEY (`CODE_ID`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door_note` ADD FOREIGN KEY (`DOOR_ID`) REFERENCES `door` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door_type` ADD FOREIGN KEY (`DOOR_ID`) REFERENCES `door` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `door_type` ADD FOREIGN KEY (`TYPE_ID`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `download` ADD FOREIGN KEY (`DOWNLOADED`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `employee` ADD FOREIGN KEY (`USER_ID`) REFERENCES `user` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `employee` ADD FOREIGN KEY (`COMPANY_ID`) REFERENCES `company` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `floorplan` ADD FOREIGN KEY (`DOOR_ID`) REFERENCES `door` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `framedetail` ADD FOREIGN KEY (`DOOR_ID`) REFERENCES `door` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `hardware` ADD FOREIGN KEY (`DOOR_ID`) REFERENCES `door` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `ink` ADD FOREIGN KEY (`DOOR_ID`) REFERENCES `door` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `inspect` ADD FOREIGN KEY (`INSPECTOR_ID`) REFERENCES `employee` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `inspect` ADD FOREIGN KEY (`INSPECTION_ID`) REFERENCES `inspection` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `inspection` ADD FOREIGN KEY (`STATUS`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `inspection` ADD FOREIGN KEY (`BUILDING_ID`) REFERENCES `building` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `inspection` ADD FOREIGN KEY (`COMPANY_ID`) REFERENCES `company` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `inspection` ADD FOREIGN KEY (`TEMPLATE_ID`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `integration` ADD FOREIGN KEY (`TYPE`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `integration` ADD FOREIGN KEY (`INSPECTION_ID`) REFERENCES `inspection` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `integration` ADD FOREIGN KEY (`STATUS`) REFERENCES `dictionary` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `picture` ADD FOREIGN KEY (`DOOR_ID`) REFERENCES `door` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `role` ADD FOREIGN KEY (`PARENT_ROLE_ID`) REFERENCES `role` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `user_file` ADD FOREIGN KEY (`USER_ID`) REFERENCES `user` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `user_role` ADD FOREIGN KEY (`ROLE_ID`) REFERENCES `role` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;