DELETE FROM `dictionary` WHERE id = 1165;
DELETE FROM `dictionary` WHERE id = 1167;
DELETE FROM `dictionary` WHERE id = 1169;
DELETE FROM `dictionary` WHERE id = 1171;
DELETE FROM `dictionary` WHERE id = 1173;
DELETE FROM `dictionary` WHERE id = 1175;
DELETE FROM `dictionary` WHERE id = 1177;
DELETE FROM `dictionary` WHERE id = 1179;
DELETE FROM `dictionary` WHERE id = 1181;
DELETE FROM `dictionary` WHERE id = 1183;
DELETE FROM `dictionary` WHERE id = 1185;
DELETE FROM `dictionary` WHERE id = 1187;
DELETE FROM `dictionary` WHERE id = 1189;
DELETE FROM `dictionary` WHERE id = 1191;
DELETE FROM `dictionary` WHERE id = 1193;
DELETE FROM `dictionary` WHERE id = 1194;
DELETE FROM `dictionary` WHERE id = 1196;
DELETE FROM `dictionary` WHERE id = 1198;
DELETE FROM `dictionary` WHERE id = 1200;
DELETE FROM `dictionary` WHERE id = 1202;
DELETE FROM `dictionary` WHERE id = 1204;
DELETE FROM `dictionary` WHERE id = 1206;
DELETE FROM `dictionary` WHERE id = 1208;
DELETE FROM `dictionary` WHERE id = 1210;
DELETE FROM `dictionary` WHERE id = 1212;
DELETE FROM `dictionary` WHERE id = 1214;
DELETE FROM `dictionary` WHERE id = 1216;
DELETE FROM `dictionary` WHERE id = 1218;
DELETE FROM `dictionary` WHERE id = 1220;
DELETE FROM `dictionary` WHERE id = 1222;
DELETE FROM `dictionary` WHERE id = 1223;
DELETE FROM `dictionary` WHERE id = 1225;
DELETE FROM `dictionary` WHERE id = 1227;
DELETE FROM `dictionary` WHERE id = 1229;
DELETE FROM `dictionary` WHERE id = 1231;
DELETE FROM `dictionary` WHERE id = 1233;
DELETE FROM `dictionary` WHERE id = 1235;
DELETE FROM `dictionary` WHERE id = 1237;
DELETE FROM `dictionary` WHERE id = 1239;
DELETE FROM `dictionary` WHERE id = 1241;
DELETE FROM `dictionary` WHERE id = 1243;
DELETE FROM `dictionary` WHERE id = 1245;
DELETE FROM `dictionary` WHERE id = 1247;
DELETE FROM `dictionary` WHERE id = 1249;
DELETE FROM `dictionary` WHERE id = 1251;
DELETE FROM `dictionary` WHERE id = 1252;
DELETE FROM `dictionary` WHERE id = 1254;
DELETE FROM `dictionary` WHERE id = 1256;
DELETE FROM `dictionary` WHERE id = 1258;
DELETE FROM `dictionary` WHERE id = 1260;
DELETE FROM `dictionary` WHERE id = 1262;
DELETE FROM `dictionary` WHERE id = 1264;
DELETE FROM `dictionary` WHERE id = 1266;
DELETE FROM `dictionary` WHERE id = 1268;
DELETE FROM `dictionary` WHERE id = 1270;
DELETE FROM `dictionary` WHERE id = 1272;
DELETE FROM `dictionary` WHERE id = 1274;
DELETE FROM `dictionary` WHERE id = 1276;
DELETE FROM `dictionary` WHERE id = 1278;
DELETE FROM `dictionary` WHERE id = 1280;
DELETE FROM `dictionary` WHERE id = 1281;
DELETE FROM `dictionary` WHERE id = 1283;
DELETE FROM `dictionary` WHERE id = 1285;
DELETE FROM `dictionary` WHERE id = 1287;
DELETE FROM `dictionary` WHERE id = 1289;
DELETE FROM `dictionary` WHERE id = 1291;
DELETE FROM `dictionary` WHERE id = 1293;
DELETE FROM `dictionary` WHERE id = 1295;
DELETE FROM `dictionary` WHERE id = 1297;
DELETE FROM `dictionary` WHERE id = 1299;
DELETE FROM `dictionary` WHERE id = 1301;
DELETE FROM `dictionary` WHERE id = 1303;
DELETE FROM `dictionary` WHERE id = 1305;
DELETE FROM `dictionary` WHERE id = 1307;
DELETE FROM `dictionary` WHERE id = 1309;
DELETE FROM `dictionary` WHERE id = 1310;
DELETE FROM `dictionary` WHERE id = 1312;
DELETE FROM `dictionary` WHERE id = 1314;
DELETE FROM `dictionary` WHERE id = 1316;
DELETE FROM `dictionary` WHERE id = 1318;
DELETE FROM `dictionary` WHERE id = 1320;
DELETE FROM `dictionary` WHERE id = 1322;
DELETE FROM `dictionary` WHERE id = 1324;
DELETE FROM `dictionary` WHERE id = 1326;
DELETE FROM `dictionary` WHERE id = 1328;
DELETE FROM `dictionary` WHERE id = 1330;
DELETE FROM `dictionary` WHERE id = 1332;
DELETE FROM `dictionary` WHERE id = 1334;
DELETE FROM `dictionary` WHERE id = 1336;
DELETE FROM `dictionary` WHERE id = 1338;

UPDATE `dictionary` SET value_order = 1 WHERE id=1166;
UPDATE `dictionary` SET value_order = 2 WHERE id=1168;
UPDATE `dictionary` SET value_order = 3 WHERE id=1170;
UPDATE `dictionary` SET value_order = 4 WHERE id=1172;
UPDATE `dictionary` SET value_order = 5 WHERE id=1174;
UPDATE `dictionary` SET value_order = 7 WHERE id=1176;
UPDATE `dictionary` SET value_order = 8 WHERE id=1178;
UPDATE `dictionary` SET value_order = 9 WHERE id=1180;
UPDATE `dictionary` SET value_order = 10 WHERE id=1182;
UPDATE `dictionary` SET value_order = 11 WHERE id=1184;
UPDATE `dictionary` SET value_order = 12 WHERE id=1186;
UPDATE `dictionary` SET value_order = 13 WHERE id=1188;
UPDATE `dictionary` SET value_order = 14 WHERE id=1190;
UPDATE `dictionary` SET value_order = 15 WHERE id=1192;

UPDATE `dictionary` SET value_order = 1 WHERE id=1195;
UPDATE `dictionary` SET value_order = 2 WHERE id=1197;
UPDATE `dictionary` SET value_order = 3 WHERE id=1199;
UPDATE `dictionary` SET value_order = 4 WHERE id=1201;
UPDATE `dictionary` SET value_order = 5 WHERE id=1203;
UPDATE `dictionary` SET value_order = 7 WHERE id=1205;
UPDATE `dictionary` SET value_order = 8 WHERE id=1207;
UPDATE `dictionary` SET value_order = 9 WHERE id=1209;
UPDATE `dictionary` SET value_order = 10 WHERE id=1211;
UPDATE `dictionary` SET value_order = 11 WHERE id=1213;
UPDATE `dictionary` SET value_order = 12 WHERE id=1215;
UPDATE `dictionary` SET value_order = 13 WHERE id=1217;
UPDATE `dictionary` SET value_order = 14 WHERE id=1219;
UPDATE `dictionary` SET value_order = 15 WHERE id=1221;

UPDATE `dictionary` SET value_order = 1 WHERE id=1224;
UPDATE `dictionary` SET value_order = 2 WHERE id=1226;
UPDATE `dictionary` SET value_order = 3 WHERE id=1228;
UPDATE `dictionary` SET value_order = 4 WHERE id=1230;
UPDATE `dictionary` SET value_order = 5 WHERE id=1232;
UPDATE `dictionary` SET value_order = 7 WHERE id=1234;
UPDATE `dictionary` SET value_order = 8 WHERE id=1236;
UPDATE `dictionary` SET value_order = 9 WHERE id=1238;
UPDATE `dictionary` SET value_order = 10 WHERE id=1240;
UPDATE `dictionary` SET value_order = 11 WHERE id=1242;
UPDATE `dictionary` SET value_order = 12 WHERE id=1244;
UPDATE `dictionary` SET value_order = 13 WHERE id=1246;
UPDATE `dictionary` SET value_order = 14 WHERE id=1248;
UPDATE `dictionary` SET value_order = 15 WHERE id=1250;

UPDATE `dictionary` SET value_order = 1 WHERE id=1253;
UPDATE `dictionary` SET value_order = 2 WHERE id=1255;
UPDATE `dictionary` SET value_order = 3 WHERE id=1257;
UPDATE `dictionary` SET value_order = 4 WHERE id=1259;
UPDATE `dictionary` SET value_order = 5 WHERE id=1261;
UPDATE `dictionary` SET value_order = 7 WHERE id=1263;
UPDATE `dictionary` SET value_order = 8 WHERE id=1265;
UPDATE `dictionary` SET value_order = 9 WHERE id=1267;
UPDATE `dictionary` SET value_order = 10 WHERE id=1269;
UPDATE `dictionary` SET value_order = 11 WHERE id=1271;
UPDATE `dictionary` SET value_order = 12 WHERE id=1273;
UPDATE `dictionary` SET value_order = 13 WHERE id=1275;
UPDATE `dictionary` SET value_order = 14 WHERE id=1277;
UPDATE `dictionary` SET value_order = 15 WHERE id=1279;

UPDATE `dictionary` SET value_order = 1 WHERE id=1282;
UPDATE `dictionary` SET value_order = 2 WHERE id=1284;
UPDATE `dictionary` SET value_order = 3 WHERE id=1286;
UPDATE `dictionary` SET value_order = 4 WHERE id=1288;
UPDATE `dictionary` SET value_order = 5 WHERE id=1290;
UPDATE `dictionary` SET value_order = 7 WHERE id=1292;
UPDATE `dictionary` SET value_order = 8 WHERE id=1294;
UPDATE `dictionary` SET value_order = 9 WHERE id=1296;
UPDATE `dictionary` SET value_order = 10 WHERE id=1298;
UPDATE `dictionary` SET value_order = 11 WHERE id=1300;
UPDATE `dictionary` SET value_order = 12 WHERE id=1302;
UPDATE `dictionary` SET value_order = 13 WHERE id=1304;
UPDATE `dictionary` SET value_order = 14 WHERE id=1306;
UPDATE `dictionary` SET value_order = 15 WHERE id=1308;

UPDATE `dictionary` SET value_order = 1 WHERE id=1311;
UPDATE `dictionary` SET value_order = 2 WHERE id=1313;
UPDATE `dictionary` SET value_order = 3 WHERE id=1315;
UPDATE `dictionary` SET value_order = 4 WHERE id=1317;
UPDATE `dictionary` SET value_order = 5 WHERE id=1319;
UPDATE `dictionary` SET value_order = 7 WHERE id=1321;
UPDATE `dictionary` SET value_order = 8 WHERE id=1323;
UPDATE `dictionary` SET value_order = 9 WHERE id=1325;
UPDATE `dictionary` SET value_order = 10 WHERE id=1327;
UPDATE `dictionary` SET value_order = 11 WHERE id=1329;
UPDATE `dictionary` SET value_order = 12 WHERE id=1331;
UPDATE `dictionary` SET value_order = 13 WHERE id=1333;
UPDATE `dictionary` SET value_order = 14 WHERE id=1335;
UPDATE `dictionary` SET value_order = 15 WHERE id=1337;

INSERT IGNORE INTO `dictionary` VALUES ('1090', 'Hinge Fraction1', '1/16\"', null, '1');
INSERT IGNORE INTO `dictionary` VALUES ('1091', 'Hinge Fraction1', '1/8\"', null, '2');
INSERT IGNORE INTO `dictionary` VALUES ('1092', 'Hinge Fraction1', '3/16\"', null, '3');
INSERT IGNORE INTO `dictionary` VALUES ('1093', 'Hinge Fraction1', '1/4\"', null, '4');
INSERT IGNORE INTO `dictionary` VALUES ('1094', 'Hinge Fraction1', '5/16\"', null, '5');
INSERT IGNORE INTO `dictionary` VALUES ('1095', 'Hinge Fraction1', '3/8\"', null, '6');
INSERT IGNORE INTO `dictionary` VALUES ('1096', 'Hinge Fraction1', '7/16\"', null, '7');
INSERT IGNORE INTO `dictionary` VALUES ('1097', 'Hinge Fraction1', '1/2\"', null, '8');
INSERT IGNORE INTO `dictionary` VALUES ('1098', 'Hinge Fraction1', '9/16\"', null, '9');
INSERT IGNORE INTO `dictionary` VALUES ('1099', 'Hinge Fraction1', '5/8\"', null, '10');
INSERT IGNORE INTO `dictionary` VALUES ('1100', 'Hinge Fraction1', '11/16\"', null, '11');
INSERT IGNORE INTO `dictionary` VALUES ('1101', 'Hinge Fraction1', '3/4\"', null, '12');
INSERT IGNORE INTO `dictionary` VALUES ('1102', 'Hinge Fraction1', '13/16\"', null, '13');
INSERT IGNORE INTO `dictionary` VALUES ('1103', 'Hinge Fraction1', '7/8\"', null, '14');
INSERT IGNORE INTO `dictionary` VALUES ('1391', 'Hinge Fraction1', '15/16\"', null, '15');

INSERT IGNORE INTO `dictionary` VALUES ('1104', 'Hinge Fraction2', '1/16\"', null, '1');
INSERT IGNORE INTO `dictionary` VALUES ('1105', 'Hinge Fraction2', '1/8\"', null, '2');
INSERT IGNORE INTO `dictionary` VALUES ('1106', 'Hinge Fraction2', '3/16\"', null, '3');
INSERT IGNORE INTO `dictionary` VALUES ('1107', 'Hinge Fraction2', '1/4\"', null, '4');
INSERT IGNORE INTO `dictionary` VALUES ('1108', 'Hinge Fraction2', '5/16\"', null, '5');
INSERT IGNORE INTO `dictionary` VALUES ('1109', 'Hinge Fraction2', '3/8\"', null, '6');
INSERT IGNORE INTO `dictionary` VALUES ('1110', 'Hinge Fraction2', '7/16\"', null, '7');
INSERT IGNORE INTO `dictionary` VALUES ('1111', 'Hinge Fraction2', '1/2\"', null, '8');
INSERT IGNORE INTO `dictionary` VALUES ('1112', 'Hinge Fraction2', '9/16\"', null, '9');
INSERT IGNORE INTO `dictionary` VALUES ('1113', 'Hinge Fraction2', '5/8\"', null, '10');
INSERT IGNORE INTO `dictionary` VALUES ('1114', 'Hinge Fraction2', '11/16\"', null, '11');
INSERT IGNORE INTO `dictionary` VALUES ('1115', 'Hinge Fraction2', '3/4\"', null, '12');
INSERT IGNORE INTO `dictionary` VALUES ('1116', 'Hinge Fraction2', '13/16\"', null, '13');
INSERT IGNORE INTO `dictionary` VALUES ('1117', 'Hinge Fraction2', '7/8\"', null, '14');
INSERT IGNORE INTO `dictionary` VALUES ('1390', 'Hinge Fraction2', '15/16\"', null, '15');

INSERT IGNORE INTO `dictionary` VALUES ('1118', 'Hinge Fraction3', '1/16\"', null, '1');
INSERT IGNORE INTO `dictionary` VALUES ('1119', 'Hinge Fraction3', '1/8\"', null, '2');
INSERT IGNORE INTO `dictionary` VALUES ('1120', 'Hinge Fraction3', '3/16\"', null, '3');
INSERT IGNORE INTO `dictionary` VALUES ('1121', 'Hinge Fraction3', '1/4\"', null, '4');
INSERT IGNORE INTO `dictionary` VALUES ('1122', 'Hinge Fraction3', '5/16\"', null, '5');
INSERT IGNORE INTO `dictionary` VALUES ('1123', 'Hinge Fraction3', '3/8\"', null, '6');
INSERT IGNORE INTO `dictionary` VALUES ('1124', 'Hinge Fraction3', '7/16\"', null, '7');
INSERT IGNORE INTO `dictionary` VALUES ('1125', 'Hinge Fraction3', '1/2\"', null, '8');
INSERT IGNORE INTO `dictionary` VALUES ('1126', 'Hinge Fraction3', '9/16\"', null, '9');
INSERT IGNORE INTO `dictionary` VALUES ('1127', 'Hinge Fraction3', '5/8\"', null, '10');
INSERT IGNORE INTO `dictionary` VALUES ('1128', 'Hinge Fraction3', '11/16\"', null, '11');
INSERT IGNORE INTO `dictionary` VALUES ('1129', 'Hinge Fraction3', '3/4\"', null, '12');
INSERT IGNORE INTO `dictionary` VALUES ('1130', 'Hinge Fraction3', '13/16\"', null, '13');
INSERT IGNORE INTO `dictionary` VALUES ('1131', 'Hinge Fraction3', '7/8\"', null, '14');
INSERT IGNORE INTO `dictionary` VALUES ('1389', 'Hinge Fraction3', '15/16\"', null, '15');

INSERT IGNORE INTO `dictionary` VALUES ('1132', 'Hinge Fraction4', '1/16\"', null, '1');
INSERT IGNORE INTO `dictionary` VALUES ('1133', 'Hinge Fraction4', '1/8\"', null, '2');
INSERT IGNORE INTO `dictionary` VALUES ('1134', 'Hinge Fraction4', '3/16\"', null, '3');
INSERT IGNORE INTO `dictionary` VALUES ('1135', 'Hinge Fraction4', '1/4\"', null, '4');
INSERT IGNORE INTO `dictionary` VALUES ('1136', 'Hinge Fraction4', '5/16\"', null, '5');
INSERT IGNORE INTO `dictionary` VALUES ('1137', 'Hinge Fraction4', '3/8\"', null, '6');
INSERT IGNORE INTO `dictionary` VALUES ('1138', 'Hinge Fraction4', '7/16\"', null, '7');
INSERT IGNORE INTO `dictionary` VALUES ('1139', 'Hinge Fraction4', '1/2\"', null, '8');
INSERT IGNORE INTO `dictionary` VALUES ('1140', 'Hinge Fraction4', '9/16\"', null, '9');
INSERT IGNORE INTO `dictionary` VALUES ('1141', 'Hinge Fraction4', '5/8\"', null, '10');
INSERT IGNORE INTO `dictionary` VALUES ('1142', 'Hinge Fraction4', '11/16\"', null, '11');
INSERT IGNORE INTO `dictionary` VALUES ('1143', 'Hinge Fraction4', '3/4\"', null, '12');
INSERT IGNORE INTO `dictionary` VALUES ('1144', 'Hinge Fraction4', '13/16\"', null, '13');
INSERT IGNORE INTO `dictionary` VALUES ('1145', 'Hinge Fraction4', '7/8\"', null, '14');
INSERT IGNORE INTO `dictionary` VALUES ('1388', 'Hinge Fraction4', '15/16\"', null, '15');

INSERT IGNORE INTO `dictionary` VALUES ('1149', 'Top To Centerline Fraction', '1/16\"', null, '1');
INSERT IGNORE INTO `dictionary` VALUES ('1150', 'Top To Centerline Fraction', '1/8\"', null, '2');
INSERT IGNORE INTO `dictionary` VALUES ('1151', 'Top To Centerline Fraction', '3/16\"', null, '3');
INSERT IGNORE INTO `dictionary` VALUES ('1152', 'Top To Centerline Fraction', '1/4\"', null, '4');
INSERT IGNORE INTO `dictionary` VALUES ('1153', 'Top To Centerline Fraction', '5/16\"', null, '5');
INSERT IGNORE INTO `dictionary` VALUES ('1154', 'Top To Centerline Fraction', '3/8\"', null, '6');
INSERT IGNORE INTO `dictionary` VALUES ('1155', 'Top To Centerline Fraction', '7/16\"', null, '7');
INSERT IGNORE INTO `dictionary` VALUES ('1156', 'Top To Centerline Fraction', '1/2\"', null, '8');
INSERT IGNORE INTO `dictionary` VALUES ('1398', 'Top To Centerline Fraction', '9/16\"', null, '9');
INSERT IGNORE INTO `dictionary` VALUES ('1399', 'Top To Centerline Fraction', '5/8\"', null, '10');
INSERT IGNORE INTO `dictionary` VALUES ('1400', 'Top To Centerline Fraction', '11/16\"', null, '11');
INSERT IGNORE INTO `dictionary` VALUES ('1401', 'Top To Centerline Fraction', '3/4\"', null, '12');
INSERT IGNORE INTO `dictionary` VALUES ('1402', 'Top To Centerline Fraction', '13/16\"', null, '13');
INSERT IGNORE INTO `dictionary` VALUES ('1403', 'Top To Centerline Fraction', '7/8\"', null, '14');
INSERT IGNORE INTO `dictionary` VALUES ('1404', 'Top To Centerline Fraction', '15/16\"', null, '15');


INSERT IGNORE INTO `dictionary` VALUES ('1166', 'Prefit Fraction X', '1/16\"', null, '1');
INSERT IGNORE INTO `dictionary` VALUES ('1168', 'Prefit Fraction X', '1/8\"', null, '2');
INSERT IGNORE INTO `dictionary` VALUES ('1170', 'Prefit Fraction X', '3/16\"', null, '3');
INSERT IGNORE INTO `dictionary` VALUES ('1172', 'Prefit Fraction X', '1/4\"', null, '4');
INSERT IGNORE INTO `dictionary` VALUES ('1174', 'Prefit Fraction X', '5/16\"', null, '5');
INSERT IGNORE INTO `dictionary` VALUES ('1396', 'Prefit Fraction X', '3/8\"', null, '6');
INSERT IGNORE INTO `dictionary` VALUES ('1176', 'Prefit Fraction X', '7/16\"', null, '7');
INSERT IGNORE INTO `dictionary` VALUES ('1178', 'Prefit Fraction X', '1/2\"', null, '8');
INSERT IGNORE INTO `dictionary` VALUES ('1180', 'Prefit Fraction X', '9/16\"', null, '9');
INSERT IGNORE INTO `dictionary` VALUES ('1182', 'Prefit Fraction X', '5/8\"', null, '10');
INSERT IGNORE INTO `dictionary` VALUES ('1184', 'Prefit Fraction X', '11/16\"', null, '11');
INSERT IGNORE INTO `dictionary` VALUES ('1186', 'Prefit Fraction X', '3/4\"', null, '12');
INSERT IGNORE INTO `dictionary` VALUES ('1188', 'Prefit Fraction X', '13/16\"', null, '13');
INSERT IGNORE INTO `dictionary` VALUES ('1190', 'Prefit Fraction X', '7/8\"', null, '14');
INSERT IGNORE INTO `dictionary` VALUES ('1192', 'Prefit Fraction X', '15/16\"', null, '15');

INSERT IGNORE INTO `dictionary` VALUES ('1195', 'Prefit Fraction Y', '1/16\"', null, '1');
INSERT IGNORE INTO `dictionary` VALUES ('1197', 'Prefit Fraction Y', '1/8\"', null, '2');
INSERT IGNORE INTO `dictionary` VALUES ('1199', 'Prefit Fraction Y', '3/16\"', null, '3');
INSERT IGNORE INTO `dictionary` VALUES ('1201', 'Prefit Fraction Y', '1/4\"', null, '4');
INSERT IGNORE INTO `dictionary` VALUES ('1203', 'Prefit Fraction Y', '5/16\"', null, '5');
INSERT IGNORE INTO `dictionary` VALUES ('1397', 'Prefit Fraction Y', '3/8\"', null, '6');
INSERT IGNORE INTO `dictionary` VALUES ('1205', 'Prefit Fraction Y', '7/16\"', null, '7');
INSERT IGNORE INTO `dictionary` VALUES ('1207', 'Prefit Fraction Y', '1/2\"', null, '8');
INSERT IGNORE INTO `dictionary` VALUES ('1209', 'Prefit Fraction Y', '9/16\"', null, '9');
INSERT IGNORE INTO `dictionary` VALUES ('1211', 'Prefit Fraction Y', '5/8\"', null, '10');
INSERT IGNORE INTO `dictionary` VALUES ('1213', 'Prefit Fraction Y', '11/16\"', null, '11');
INSERT IGNORE INTO `dictionary` VALUES ('1215', 'Prefit Fraction Y', '3/4\"', null, '12');
INSERT IGNORE INTO `dictionary` VALUES ('1217', 'Prefit Fraction Y', '13/16\"', null, '13');
INSERT IGNORE INTO `dictionary` VALUES ('1219', 'Prefit Fraction Y', '7/8\"', null, '14');
INSERT IGNORE INTO `dictionary` VALUES ('1221', 'Prefit Fraction Y', '15/16\"', null, '15');

INSERT IGNORE INTO `dictionary` VALUES ('1224', 'Frame Opening Fraction X', '1/16\"', null, '1');
INSERT IGNORE INTO `dictionary` VALUES ('1226', 'Frame Opening Fraction X', '1/8\"', null, '2');
INSERT IGNORE INTO `dictionary` VALUES ('1228', 'Frame Opening Fraction X', '3/16\"', null, '3');
INSERT IGNORE INTO `dictionary` VALUES ('1230', 'Frame Opening Fraction X', '1/4\"', null, '4');
INSERT IGNORE INTO `dictionary` VALUES ('1232', 'Frame Opening Fraction X', '5/16\"', null, '5');
INSERT IGNORE INTO `dictionary` VALUES ('1392', 'Frame Opening Fraction X', '3/8\"', null, '6');
INSERT IGNORE INTO `dictionary` VALUES ('1234', 'Frame Opening Fraction X', '7/16\"', null, '7');
INSERT IGNORE INTO `dictionary` VALUES ('1236', 'Frame Opening Fraction X', '1/2\"', null, '8');
INSERT IGNORE INTO `dictionary` VALUES ('1238', 'Frame Opening Fraction X', '9/16\"', null, '9');
INSERT IGNORE INTO `dictionary` VALUES ('1240', 'Frame Opening Fraction X', '5/8\"', null, '10');
INSERT IGNORE INTO `dictionary` VALUES ('1242', 'Frame Opening Fraction X', '11/16\"', null, '11');
INSERT IGNORE INTO `dictionary` VALUES ('1244', 'Frame Opening Fraction X', '3/4\"', null, '12');
INSERT IGNORE INTO `dictionary` VALUES ('1246', 'Frame Opening Fraction X', '13/16\"', null, '13');
INSERT IGNORE INTO `dictionary` VALUES ('1248', 'Frame Opening Fraction X', '7/8\"', null, '14');
INSERT IGNORE INTO `dictionary` VALUES ('1250', 'Frame Opening Fraction X', '15/16\"', null, '15');

INSERT IGNORE INTO `dictionary` VALUES ('1253', 'Frame Opening Fraction Y', '1/16\"', null, '1');
INSERT IGNORE INTO `dictionary` VALUES ('1255', 'Frame Opening Fraction Y', '1/8\"', null, '2');
INSERT IGNORE INTO `dictionary` VALUES ('1257', 'Frame Opening Fraction Y', '3/16\"', null, '3');
INSERT IGNORE INTO `dictionary` VALUES ('1259', 'Frame Opening Fraction Y', '1/4\"', null, '4');
INSERT IGNORE INTO `dictionary` VALUES ('1261', 'Frame Opening Fraction Y', '5/16\"', null, '5');
INSERT IGNORE INTO `dictionary` VALUES ('1393', 'Frame Opening Fraction Y', '3/8\"', null, '6');
INSERT IGNORE INTO `dictionary` VALUES ('1263', 'Frame Opening Fraction Y', '7/16\"', null, '7');
INSERT IGNORE INTO `dictionary` VALUES ('1265', 'Frame Opening Fraction Y', '1/2\"', null, '8');
INSERT IGNORE INTO `dictionary` VALUES ('1267', 'Frame Opening Fraction Y', '9/16\"', null, '9');
INSERT IGNORE INTO `dictionary` VALUES ('1269', 'Frame Opening Fraction Y', '5/8\"', null, '10');
INSERT IGNORE INTO `dictionary` VALUES ('1271', 'Frame Opening Fraction Y', '11/16\"', null, '11');
INSERT IGNORE INTO `dictionary` VALUES ('1273', 'Frame Opening Fraction Y', '3/4\"', null, '12');
INSERT IGNORE INTO `dictionary` VALUES ('1275', 'Frame Opening Fraction Y', '13/16\"', null, '13');
INSERT IGNORE INTO `dictionary` VALUES ('1277', 'Frame Opening Fraction Y', '7/8\"', null, '14');
INSERT IGNORE INTO `dictionary` VALUES ('1279', 'Frame Opening Fraction Y', '15/16\"', null, '15');

INSERT IGNORE INTO `dictionary` VALUES ('1282', 'Lite Cutout Fraction X', '1/16\"', null, '1');
INSERT IGNORE INTO `dictionary` VALUES ('1284', 'Lite Cutout Fraction X', '1/8\"', null, '2');
INSERT IGNORE INTO `dictionary` VALUES ('1286', 'Lite Cutout Fraction X', '3/16\"', null, '3');
INSERT IGNORE INTO `dictionary` VALUES ('1288', 'Lite Cutout Fraction X', '1/4\"', null, '4');
INSERT IGNORE INTO `dictionary` VALUES ('1290', 'Lite Cutout Fraction X', '5/16\"', null, '5');
INSERT IGNORE INTO `dictionary` VALUES ('1394', 'Lite Cutout Fraction X', '3/8\"', null, '6');
INSERT IGNORE INTO `dictionary` VALUES ('1292', 'Lite Cutout Fraction X', '7/16\"', null, '7');
INSERT IGNORE INTO `dictionary` VALUES ('1294', 'Lite Cutout Fraction X', '1/2\"', null, '8');
INSERT IGNORE INTO `dictionary` VALUES ('1296', 'Lite Cutout Fraction X', '9/16\"', null, '9');
INSERT IGNORE INTO `dictionary` VALUES ('1298', 'Lite Cutout Fraction X', '5/8\"', null, '10');
INSERT IGNORE INTO `dictionary` VALUES ('1300', 'Lite Cutout Fraction X', '11/16\"', null, '11');
INSERT IGNORE INTO `dictionary` VALUES ('1302', 'Lite Cutout Fraction X', '3/4\"', null, '12');
INSERT IGNORE INTO `dictionary` VALUES ('1304', 'Lite Cutout Fraction X', '13/16\"', null, '13');
INSERT IGNORE INTO `dictionary` VALUES ('1306', 'Lite Cutout Fraction X', '7/8\"', null, '14');
INSERT IGNORE INTO `dictionary` VALUES ('1308', 'Lite Cutout Fraction X', '15/16\"', null, '15');

INSERT IGNORE INTO `dictionary` VALUES ('1311', 'Lite Cutout Fraction Y', '1/16\"', null, '1');
INSERT IGNORE INTO `dictionary` VALUES ('1313', 'Lite Cutout Fraction Y', '1/8\"', null, '2');
INSERT IGNORE INTO `dictionary` VALUES ('1315', 'Lite Cutout Fraction Y', '3/16\"', null, '3');
INSERT IGNORE INTO `dictionary` VALUES ('1317', 'Lite Cutout Fraction Y', '1/4\"', null, '4');
INSERT IGNORE INTO `dictionary` VALUES ('1319', 'Lite Cutout Fraction Y', '5/16\"', null, '5');
INSERT IGNORE INTO `dictionary` VALUES ('1395', 'Lite Cutout Fraction Y', '3/8\"', null, '6');
INSERT IGNORE INTO `dictionary` VALUES ('1321', 'Lite Cutout Fraction Y', '7/16\"', null, '7');
INSERT IGNORE INTO `dictionary` VALUES ('1323', 'Lite Cutout Fraction Y', '1/2\"', null, '8');
INSERT IGNORE INTO `dictionary` VALUES ('1325', 'Lite Cutout Fraction Y', '9/16\"', null, '9');
INSERT IGNORE INTO `dictionary` VALUES ('1327', 'Lite Cutout Fraction Y', '5/8\"', null, '10');
INSERT IGNORE INTO `dictionary` VALUES ('1329', 'Lite Cutout Fraction Y', '11/16\"', null, '11');
INSERT IGNORE INTO `dictionary` VALUES ('1331', 'Lite Cutout Fraction Y', '3/4\"', null, '12');
INSERT IGNORE INTO `dictionary` VALUES ('1333', 'Lite Cutout Fraction Y', '13/16\"', null, '13');
INSERT IGNORE INTO `dictionary` VALUES ('1335', 'Lite Cutout Fraction Y', '7/8\"', null, '14');
INSERT IGNORE INTO `dictionary` VALUES ('1337', 'Lite Cutout Fraction Y', '15/16\"', null, '15');

INSERT IGNORE INTO `dictionary` VALUES ('1339', 'Lockstile Fraction', '1/16\"', null, '1');
INSERT IGNORE INTO `dictionary` VALUES ('1340', 'Lockstile Fraction', '1/8\"', null, '2');
INSERT IGNORE INTO `dictionary` VALUES ('1341', 'Lockstile Fraction', '3/16\"', null, '3');
INSERT IGNORE INTO `dictionary` VALUES ('1342', 'Lockstile Fraction', '1/4\"', null, '4');
INSERT IGNORE INTO `dictionary` VALUES ('1343', 'Lockstile Fraction', '5/16\"', null, '5');
INSERT IGNORE INTO `dictionary` VALUES ('1344', 'Lockstile Fraction', '3/8\"', null, '6');
INSERT IGNORE INTO `dictionary` VALUES ('1345', 'Lockstile Fraction', '7/16\"', null, '7');
INSERT IGNORE INTO `dictionary` VALUES ('1346', 'Lockstile Fraction', '1/2\"', null, '8');
INSERT IGNORE INTO `dictionary` VALUES ('1347', 'Lockstile Fraction', '9/16\"', null, '9');
INSERT IGNORE INTO `dictionary` VALUES ('1348', 'Lockstile Fraction', '5/8\"', null, '10');
INSERT IGNORE INTO `dictionary` VALUES ('1349', 'Lockstile Fraction', '11/16\"', null, '11');
INSERT IGNORE INTO `dictionary` VALUES ('1350', 'Lockstile Fraction', '3/4\"', null, '12');
INSERT IGNORE INTO `dictionary` VALUES ('1351', 'Lockstile Fraction', '13/16\"', null, '13');
INSERT IGNORE INTO `dictionary` VALUES ('1352', 'Lockstile Fraction', '7/8\"', null, '14');
INSERT IGNORE INTO `dictionary` VALUES ('1386', 'Lockstile Fraction', '15/16\"', null, '15');

INSERT IGNORE INTO `dictionary` VALUES ('1353', 'Top Rail Fraction', '1/16\"', null, '1');
INSERT IGNORE INTO `dictionary` VALUES ('1354', 'Top Rail Fraction', '1/8\"', null, '2');
INSERT IGNORE INTO `dictionary` VALUES ('1355', 'Top Rail Fraction', '3/16\"', null, '3');
INSERT IGNORE INTO `dictionary` VALUES ('1356', 'Top Rail Fraction', '1/4\"', null, '4');
INSERT IGNORE INTO `dictionary` VALUES ('1357', 'Top Rail Fraction', '5/16\"', null, '5');
INSERT IGNORE INTO `dictionary` VALUES ('1358', 'Top Rail Fraction', '3/8\"', null, '6');
INSERT IGNORE INTO `dictionary` VALUES ('1359', 'Top Rail Fraction', '7/16\"', null, '7');
INSERT IGNORE INTO `dictionary` VALUES ('1360', 'Top Rail Fraction', '1/2\"', null, '8');
INSERT IGNORE INTO `dictionary` VALUES ('1361', 'Top Rail Fraction', '9/16\"', null, '9');
INSERT IGNORE INTO `dictionary` VALUES ('1362', 'Top Rail Fraction', '5/8\"', null, '10');
INSERT IGNORE INTO `dictionary` VALUES ('1363', 'Top Rail Fraction', '11/16\"', null, '11');
INSERT IGNORE INTO `dictionary` VALUES ('1364', 'Top Rail Fraction', '3/4\"', null, '12');
INSERT IGNORE INTO `dictionary` VALUES ('1365', 'Top Rail Fraction', '13/16\"', null, '13');
INSERT IGNORE INTO `dictionary` VALUES ('1366', 'Top Rail Fraction', '7/8\"', null, '14');
INSERT IGNORE INTO `dictionary` VALUES ('1385', 'Top Rail Fraction', '15/16\"', null, '15');


INSERT IGNORE INTO `dictionary` VALUES ('1382', 'Frame Fraction', '1/16\"', null, '1');
INSERT IGNORE INTO `dictionary` VALUES ('1371', 'Frame Fraction', '1/8\"', null, '2');
INSERT IGNORE INTO `dictionary` VALUES ('1374', 'Frame Fraction', '3/16\"', null, '3');
INSERT IGNORE INTO `dictionary` VALUES ('1370', 'Frame Fraction', '1/4\"', null, '4');
INSERT IGNORE INTO `dictionary` VALUES ('1377', 'Frame Fraction', '5/16\"', null, '5');
INSERT IGNORE INTO `dictionary` VALUES ('1376', 'Frame Fraction', '3/8\"', null, '6');
INSERT IGNORE INTO `dictionary` VALUES ('1379', 'Frame Fraction', '7/16\"', null, '7');
INSERT IGNORE INTO `dictionary` VALUES ('1369', 'Frame Fraction', '1/2\"', null, '8');
INSERT IGNORE INTO `dictionary` VALUES ('1381', 'Frame Fraction', '9/16\"', null, '9');
INSERT IGNORE INTO `dictionary` VALUES ('1378', 'Frame Fraction', '5/8\"', null, '10');
INSERT IGNORE INTO `dictionary` VALUES ('1372', 'Frame Fraction', '11/16\"', null, '11');
INSERT IGNORE INTO `dictionary` VALUES ('1375', 'Frame Fraction', '3/4\"', null, '12');
INSERT IGNORE INTO `dictionary` VALUES ('1373', 'Frame Fraction', '13/16\"', null, '13');
INSERT IGNORE INTO `dictionary` VALUES ('1380', 'Frame Fraction', '7/8\"', null, '14');
INSERT IGNORE INTO `dictionary` VALUES ('1387', 'Frame Fraction', '15/16\"', null, '15');