<div class="content-box">
	<h3 id="buildings" class="content-box-header bg-primary" style="text-align: left;">
		<i class="glyph-icon icon-file-o"></i>
		USER FILES
		<div class="header-buttons-separator">
			<!-- <a class="icon-separator" href="javascript:bratiliusDialog.showSearch(
				'<?php //echo App::baseUrl() ?>/userfile/search?_model=user_file', 'cmp_user_file');">
				<i class="glyph-icon icon-search"></i>
            </a> -->
            <a class="icon-separator" href="<?php echo App::baseUrl() ?>/userfile/excelexport?gridId=user_file" target='_blank'>
				<i class="glyph-icon fa-file-excel-o"></i>
			</a>
            <div class="table-maindiv">
            <input type="text" name="search-inspection" class="searchtable" id="search_inspection" placeholder="Search for User">
			<a href="#" class="" id="searchInspectionBtn" style="color:#7da3c7;"><i class="glyph-icon icon-search"></i></a>	
           </div>

            <? /*
			<a class="icon-separator" href="javascript:cmp_user_file.showNewDialog();">
				<i class="glyph-icon icon-plus"></i>
            </a>
			 * 
			 */ ?>
		</div>
	</h3>
	
	<div class="content-box-wrapper">
		<div class="row">
			<div id="list_of_user_files" jsId="list_of_user_files" dojoType="dijit.layout.ContentPane" href="<?= App::baseUrl() ?>/userfile/userfiles"></div>
		</div>
	</div>
	
</div>


<script type="text/javascript">
	$(document).ready(function() {

		$("#searchInspectionBtn").click(function(e){
			searchInspection();	
		});

		$('#search_inspection').on('keypress', function(e) {           
			var code = e.keyCode || e.which;
			if(code==13){
				searchInspection();  
			}
		});
	});


	function searchInspection(){
		var search = $("#search_inspection").val();
		bratiliusDialog.setGrid("cmp_user_file");
		var elements = {
			"FILE_NAME":"*"+search+"*"
		}
	
		bratiliusDialog.executeSearch(elements)
	}

</script>